# -*- coding: utf-8 -*-
"""Itens de FAQ de preparo de exames (grupo 1) para a base de conhecimento do MedIA."""

_IGASTRO = ("iGastroProcto - Exames e Preparos", "https://www.igastroprocto.com.br/exames-e-preparos/")
_IGESP = ("Hospital IGESP - Exames Endoscópicos", "https://hospitaligesp.com.br/exames-endoscopicos/")
_ACC = ("A.C.Camargo Cancer Center - Colonoscopia virtual por tomografia", "https://accamargo.org.br/pacientes/preparo-de-exames/tomografia-computadorizada-colonoscopia-virtual")
_CEFIDI = ("CEFIDI - Preparo do teste H. pylori", "https://cefidi.com.br/preparos/teste-h-pylori/")
_SAOLUIZ = ("Rede D'Or São Luiz - Raio-X de Defecograma", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-defecograma")
_CUF = ("CUF - Enteroscopia de balão", "https://www.cuf.pt/marcacoes/exames/gastrenterologia-enteroscopia-de-balao")

ITENS = [
    # ---------------- Retossigmoidoscopia ----------------
    ("Retossigmoidoscopia", "Preciso ficar em jejum para a retossigmoidoscopia?",
     "Sim, a clínica pede jejum antes do exame. O tempo para alimentos sólidos e para líquidos vem no seu preparo, então siga exatamente o que foi informado. Assim o exame fica mais seguro e a visão do intestino fica melhor.",
     _IGESP),
    ("Retossigmoidoscopia", "Como é feita a limpeza do intestino para a retossigmoidoscopia?",
     "Depende do serviço. Alguns usam enemas aplicados antes do exame e outros pedem o mesmo preparo da colonoscopia. Siga o modelo que veio na sua orientação e avise a equipe da clínica se tiver dificuldade para concluir.",
     _IGESP),
    ("Retossigmoidoscopia", "Preciso levar acompanhante para a retossigmoidoscopia?",
     "Sim, em geral é exigido um acompanhante adulto, porque o exame pode ser feito com sedação. Combine com alguém de confiança antes do dia marcado para que você volte para casa com segurança.",
     _IGASTRO),
    ("Retossigmoidoscopia", "Tomo anticoagulante, o que faço antes da retossigmoidoscopia?",
     "Avise a equipe da clínica que você usa anticoagulante ou outro remédio que afina o sangue. Se for preciso suspender, isso será feito pelo tempo indicado no seu preparo. Não interrompa por conta própria.",
     _IGASTRO),
    ("Retossigmoidoscopia", "O que acontece depois da retossigmoidoscopia?",
     "Depois da sedação você fica em observação até se recuperar bem. Não dirija no mesmo dia e volte para casa acompanhado. Avise a equipe se sentir dor forte na barriga ou sangramento que preocupe.",
     _IGASTRO),

    # ---------------- Enteroscopia ----------------
    ("Enteroscopia", "Como é o jejum e o preparo para a enteroscopia?",
     "Depende da via do exame. Quando ele é feito pela boca, o preparo é o jejum indicado. Quando é feito pelo ânus, você segue uma dieta sem resíduos e faz a limpeza do intestino, parecida com a da colonoscopia. Siga o tempo e as orientações do seu preparo.",
     _CUF),
    ("Enteroscopia", "Vou ficar sedado na enteroscopia? Vou sentir dor?",
     "O exame costuma ser feito com sedação profunda ou anestesia geral, então você fica dormindo e não acompanha o procedimento. Ele é mais demorado que uma endoscopia comum. Depois, algum enjoo e desconforto na barriga são possíveis e passam.",
     _CUF),
    ("Enteroscopia", "Preciso de acompanhante na enteroscopia?",
     "Sim, é recomendado ter alguém com você para ajudar na volta para casa. Em geral não é preciso ficar internado depois. Combine isso com antecedência com alguém de confiança.",
     _CUF),
    ("Enteroscopia", "Posso voltar às minhas atividades depois da enteroscopia?",
     "Depois de se recuperar do efeito da sedação, você vai para casa com o seu acompanhante e pode retomar as atividades aos poucos. Não dirija no mesmo dia. Siga as orientações que a equipe entregar na alta.",
     _CUF),
    ("Enteroscopia", "Quais sinais de alerta devo observar depois da enteroscopia?",
     "Procure atendimento se tiver febre, dor forte na barriga ou fezes muito escuras, quase pretas. Enjoo, vômito e desconforto leve são comuns e costumam passar sozinhos. Avise a equipe da clínica sobre qualquer sintoma que te preocupe.",
     _CUF),

    # ---------------- Cápsula endoscópica ----------------
    ("Cápsula endoscópica", "Preciso de sedação para engolir a cápsula endoscópica?",
     "Não, o exame não usa sedação profunda. Você engole a cápsula com um pouco de líquido e segue com a rotina indicada pela equipe durante o exame.",
     _IGASTRO),
    ("Cápsula endoscópica", "Como é o preparo da cápsula endoscópica?",
     "Em geral há uma dieta líquida clara antes do exame e um jejum completo até engolir a cápsula. Os tempos exatos estão no seu preparo, então siga com atenção para que as imagens saiam boas.",
     _IGASTRO),
    ("Cápsula endoscópica", "Preciso parar algum remédio antes da cápsula endoscópica?",
     "Suplementos de ferro costumam precisar de suspensão pelo tempo indicado no seu preparo. Para os outros remédios de uso contínuo, siga a orientação que recebeu e avise a equipe da clínica se tiver dúvida sobre algum deles.",
     _IGASTRO),
    ("Cápsula endoscópica", "Preciso de acompanhante para a cápsula endoscópica?",
     "Para adultos, em geral não é obrigatório. A clínica recomenda acompanhante para menores de idade. Veja o que consta na sua orientação de agendamento.",
     _IGASTRO),
    ("Cápsula endoscópica", "Posso voltar à rotina depois da cápsula endoscópica?",
     "Sim, você é liberado para as atividades normais. O resultado sai no prazo informado pela clínica, e a equipe explica como retirar o resultado.",
     _IGASTRO),

    # ---------------- Ecoendoscopia ----------------
    ("Ecoendoscopia", "Como funciona o jejum para a ecoendoscopia?",
     "A clínica pede jejum, com um tempo para alimentos sólidos e outro para líquidos. Os prazos aparecem no seu preparo, então siga exatamente o que foi informado para o exame ser feito com segurança.",
     _IGESP),
    ("Ecoendoscopia", "Tomo remédio para o estômago, preciso parar antes da ecoendoscopia?",
     "Alguns serviços pedem a suspensão de medicamentos para o estômago antes do exame, pelo tempo indicado no seu preparo. Siga o que está escrito e avise a equipe da clínica sobre todos os remédios que você usa.",
     _IGESP),
    ("Ecoendoscopia", "Uso anticoagulante, isso interfere na ecoendoscopia?",
     "Pode interferir. Avise a equipe da clínica sobre anticoagulantes e outros remédios que afinam o sangue. Se for preciso suspender, será pelo tempo indicado no seu preparo, e não deve ser feito por conta própria.",
     _IGESP),
    ("Ecoendoscopia", "Preciso de acompanhante na ecoendoscopia?",
     "Sim, é necessário um acompanhante adulto. Ele te ajuda na volta para casa depois do exame. Combine isso com antecedência.",
     _IGESP),
    ("Ecoendoscopia", "Posso dirigir depois da ecoendoscopia?",
     "Não. O exame costuma ser feito com sedação, e por isso a orientação é não dirigir depois. Volte para casa com o seu acompanhante e descanse pelo resto do dia.",
     _IGESP),

    # ---------------- CPRE ----------------
    ("CPRE (colangiopancreatografia retrógrada endoscópica)", "Preciso ficar em jejum para a CPRE?",
     "Sim, a CPRE exige jejum de alimentos sólidos e de líquidos. Os tempos estão no seu preparo, e é importante segui-los para o exame ser seguro e o estômago estar vazio.",
     _IGESP),
    ("CPRE (colangiopancreatografia retrógrada endoscópica)", "Uso anticoagulante, o que faço antes da CPRE?",
     "Avise a equipe da clínica. Os anticoagulantes costumam ser suspensos antes do exame, pelo tempo indicado no seu preparo. Não pare nem retome por conta própria.",
     _IGESP),
    ("CPRE (colangiopancreatografia retrógrada endoscópica)", "Preciso de acompanhante na CPRE?",
     "Sim, é necessário um acompanhante adulto, porque o exame é feito com sedação. Combine com alguém antes do dia marcado.",
     _IGESP),
    ("CPRE (colangiopancreatografia retrógrada endoscópica)", "Vou ser sedado na CPRE? Posso dirigir depois?",
     "A CPRE é feita com sedação, então você fica tranquilo durante o exame. Depois dele, não dirija e volte para casa com o seu acompanhante.",
     _IGESP),
    ("CPRE (colangiopancreatografia retrógrada endoscópica)", "O que devo observar depois da CPRE?",
     "Depois do exame você fica em observação até se recuperar da sedação. Em casa, avise a equipe da clínica se sentir dor forte na barriga, febre ou vômitos que não passam.",
     _IGESP),

    # ---------------- Manometria esofágica ----------------
    ("Manometria esofágica", "Preciso de jejum para a manometria esofágica?",
     "Sim, é preciso jejum de alimentos sólidos e de líquidos, cada um pelo tempo indicado no seu preparo. Siga esses prazos com atenção para que o exame possa ser feito.",
     _IGASTRO),
    ("Manometria esofágica", "Preciso parar algum remédio antes da manometria esofágica?",
     "Sim, alguns. Os antiácidos e o remédio que estimula o esvaziamento do estômago costumam ser suspensos, cada um pelo tempo indicado no seu preparo. Avise a equipe da clínica sobre os outros remédios que usa.",
     _IGASTRO),
    ("Manometria esofágica", "Posso fazer a manometria esofágica se estiver gripado ou com nariz entupido?",
     "O ideal é avisar a equipe da clínica antes. O serviço pede para não fazer o exame com gripe ou rinite ativa, porque o exame usa a passagem do nariz. Podem reagendar para outro dia.",
     _IGASTRO),
    ("Manometria esofágica", "Preciso de sedação ou acompanhante na manometria esofágica?",
     "Não, o exame é feito sem sedação, e em geral não é obrigatório ter acompanhante. Você é liberado logo depois e o resultado sai no prazo informado pela clínica.",
     _IGASTRO),

    # ---------------- pHmetria e impedanciometria ----------------
    ("pHmetria e impedanciometria esofágica", "Preciso de jejum para a pHmetria esofágica?",
     "Sim, é preciso jejum de alimentos sólidos e de líquidos, cada um pelo tempo do seu preparo. Siga esses prazos e leve as dúvidas para a equipe da clínica antes de começar.",
     _IGASTRO),
    ("pHmetria e impedanciometria esofágica", "Quais remédios preciso suspender antes da pHmetria?",
     "Antiácidos e o remédio que estimula o esvaziamento do estômago costumam ser suspensos, cada um pelo tempo indicado no seu preparo. Avise a equipe sobre qualquer outro medicamento que use.",
     _IGASTRO),
    ("pHmetria e impedanciometria esofágica", "Preciso ser sedado ou ter acompanhante na pHmetria?",
     "Não, não há sedação e em geral o acompanhante não é obrigatório. Você segue com as atividades do período de registro conforme a equipe orientar.",
     _IGASTRO),
    ("pHmetria e impedanciometria esofágica", "Preciso voltar à clínica depois da pHmetria?",
     "Sim, o equipamento fica com você durante o período de registro e depois você retorna para retirá-lo. O resultado sai no prazo informado pela clínica.",
     _IGASTRO),

    # ---------------- Manometria anorretal ----------------
    ("Manometria anorretal", "Preciso de jejum para a manometria anorretal?",
     "Não, o exame é feito sem jejum. Você pode se alimentar normalmente, a menos que o seu preparo diga outra coisa.",
     _IGASTRO),
    ("Manometria anorretal", "Posso usar laxante antes da manometria anorretal?",
     "O serviço pede para evitar laxantes pelo tempo indicado no seu preparo. Também pode haver a aplicação de um supositório antes do exame. Siga o que estiver escrito na sua orientação.",
     _IGASTRO),
    ("Manometria anorretal", "Preciso parar algum remédio antes da manometria anorretal?",
     "Em geral não há remédio específico para suspender. Mesmo assim, avise a equipe da clínica sobre todos os medicamentos que você usa.",
     _IGASTRO),
    ("Manometria anorretal", "Preciso de sedação ou acompanhante na manometria anorretal?",
     "Não há sedação. A clínica recomenda acompanhante para mulheres, e para as demais pessoas não é obrigatório. Depois do exame você é liberado na hora.",
     _IGASTRO),

    # ---------------- Defecografia ----------------
    ("Defecografia", "Preciso ficar em jejum para a defecografia?",
     "Não, não é preciso jejum nem preparo intestinal específico. Siga apenas o que constar na orientação do seu agendamento.",
     _SAOLUIZ),
    ("Defecografia", "Continuo tomando meus remédios normalmente antes da defecografia?",
     "Sim, você mantém os seus medicamentos habituais. Avise a equipe da clínica se tiver alguma dúvida específica sobre algum deles.",
     _SAOLUIZ),
    ("Defecografia", "Vou precisar beber contraste antes da defecografia?",
     "Sim, na unidade você bebe um contraste à base de bário pelo tempo indicado antes do exame. Por isso é importante chegar com antecedência, como pede a orientação do seu agendamento.",
     _SAOLUIZ),
    ("Defecografia", "Que roupa devo usar na defecografia?",
     "Escolha uma roupa confortável e tire objetos de metal, como cinto, anéis e brincos, antes do exame. Leve também o pedido, os documentos e imagens de exames anteriores, se tiver.",
     _SAOLUIZ),
    ("Defecografia", "Posso fazer defecografia se estiver grávida?",
     "O exame usa raios-X e não deve ser feito por gestantes ou por quem suspeita de gravidez. Avise o técnico antes de começar, caso exista essa possibilidade.",
     _SAOLUIZ),
    ("Defecografia", "Tenho intestino preso, tem algum cuidado depois da defecografia?",
     "Depois do exame, quem tem constipação pode receber orientações extras por causa do contraste. Siga o que a equipe disser na saída e avise se o intestino não funcionar como de costume.",
     _SAOLUIZ),

    # ---------------- Teste respiratório (hidrogênio expirado) ----------------
    ("Teste respiratório (hidrogênio expirado: lactose, frutose, SIBO)", "Preciso de jejum para o teste respiratório de hidrogênio?",
     "Sim, é preciso jejum antes do teste, pelo tempo indicado no seu preparo. Antes disso, costuma haver também uma dieta que evita alimentos que fermentam. Siga tudo à risca para o resultado ser confiável.",
     _IGASTRO),
    ("Teste respiratório (hidrogênio expirado: lactose, frutose, SIBO)", "Posso tomar antibiótico ou probiótico antes do teste respiratório?",
     "Antibióticos devem ser evitados por um período antes do teste, e probióticos costumam ser suspensos antes. Os prazos estão no seu preparo. Avise a equipe da clínica se usou algum deles recentemente.",
     _IGASTRO),
    ("Teste respiratório (hidrogênio expirado: lactose, frutose, SIBO)", "O teste respiratório de hidrogênio é demorado?",
     "É um exame mais longo do que se imagina, porque são feitas várias coletas do ar que você sopra, ao longo do teste. Leve algo para se distrair enquanto espera, respeitando o que a equipe permitir.",
     _IGASTRO),
    ("Teste respiratório (hidrogênio expirado: lactose, frutose, SIBO)", "Preciso de sedação ou acompanhante no teste respiratório?",
     "Não, não há sedação e o acompanhante não é obrigatório. Você é liberado ao terminar e o resultado sai no prazo informado pela clínica.",
     _IGASTRO),

    # ---------------- Teste respiratório da ureia ----------------
    ("Teste respiratório da ureia (H. pylori)", "Preciso de jejum para o teste respiratório da ureia?",
     "Sim, é preciso jejum pelo tempo indicado no seu preparo, que costuma ser menor para crianças. Siga o que estiver na sua orientação.",
     _CEFIDI),
    ("Teste respiratório da ureia (H. pylori)", "Posso tomar omeprazol ou antibiótico antes do teste da ureia?",
     "Antibióticos e remédios que reduzem a acidez do estômago, como omeprazol e lansoprazol, devem ficar de fora por um período antes do teste. O prazo está no seu preparo. Antiácidos como a famotidina não atrapalham o resultado.",
     _CEFIDI),
    ("Teste respiratório da ureia (H. pylori)", "Posso tomar refrigerante ou fumar antes do teste da ureia?",
     "Não. Evite bebidas com gás e cigarro antes do exame e também entre as duas coletas de ar. Isso ajuda o resultado a sair correto.",
     _CEFIDI),
    ("Teste respiratório da ureia (H. pylori)", "Como é feito o teste respiratório da ureia?",
     "Você sopra em uma bolsa para a primeira coleta e depois toma um líquido com ureia. Após um intervalo curto, sopra em outra bolsa. É um exame simples, rápido e sem agulhas.",
     _CEFIDI),
    ("Teste respiratório da ureia (H. pylori)", "O que devo levar para o teste respiratório da ureia?",
     "Leve o pedido, a autorização do convênio se for necessária, e resultados anteriores de endoscopia com biópsia ou de outros testes para H. pylori, se você tiver.",
     _CEFIDI),
    ("Teste respiratório da ureia (H. pylori)", "Preciso de acompanhante no teste respiratório da ureia?",
     "Só é necessário para crianças e idosos. Adultos costumam ir sozinhos, porque não há sedação.",
     _CEFIDI),

    # ---------------- Colonografia por tomografia ----------------
    ("Colonografia por tomografia (colonoscopia virtual)", "Que roupa devo usar na colonoscopia virtual?",
     "Use roupas confortáveis e sem metal, como calça de moletom ou de malha. Evite peças com zíper, botões e adereços.",
     _ACC),
    ("Colonografia por tomografia (colonoscopia virtual)", "Como é o preparo da colonoscopia virtual?",
     "O preparo inclui laxantes por via oral e uma dieta líquida antes do exame. O passo a passo detalhado é entregue depois do agendamento, junto com o contraste que você toma. Siga esse material com atenção.",
     _ACC),
    ("Colonografia por tomografia (colonoscopia virtual)", "Vou tomar contraste na colonoscopia virtual?",
     "Sim, existe um contraste de uso oral que faz parte do preparo. A clínica explica como e quando retirar e tomar. Se ficar em dúvida, avise a equipe da clínica antes do exame.",
     _ACC),
    ("Colonografia por tomografia (colonoscopia virtual)", "O que devo levar para a colonoscopia virtual?",
     "Leve exames de imagem anteriores da região, mesmo de outros locais, se você tiver. Chegue com antecedência, seguindo a confirmação do agendamento, para fazer a recepção e a triagem com tranquilidade.",
     _ACC),
]
