# -*- coding: utf-8 -*-
"""Itens de FAQ de preparo de exames (grupo 2)."""

_USG = ("POP HUAB-UFRN/EBSERH - Orientações de preparo e realização de ultrassonografia", "https://www.gov.br/hubrasil/pt-br/hospitais-universitarios/regiao-nordeste/huab-ufrn/documentos-institucionais/arquivos-documentos-institucionais-geral/pop-udide-079-orientacoes-sobre-indicacao-preparo-e-realizacao-dos-exames-de-ultrassonografia.pdf")
_URO = ("A.C.Camargo Cancer Center - Urotomografia", "https://accamargo.org.br/pacientes/preparo-de-exames/tomografia-computadorizada-vias-urinarias-urotomografia")
_ENT = ("Rede D'Or São Luiz - Enterografia por tomografia computadorizada", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/tomografia-computadorizada/enterografia-por-tomografia-computadorizada")
_ANG = ("AMD Saúde - Angiotomografia", "https://amdsaude.com.br/o-que-e-a-angiotomografia/")
_SED = ("A.C.Camargo Cancer Center - Anestesia para ressonância magnética", "https://accamargo.org.br/pacientes/preparo-de-exames/anestesia-para-exames-de-ressonancia-magnetica")
_COL = ("A.C.Camargo Cancer Center - Colangiorressonância", "https://accamargo.org.br/pacientes/preparo-de-exames/ressonancia-magnetica-colangiorressonancia")

ITENS = [
    # Ultrassonografia de abdome superior
    ("Ultrassonografia de abdome superior",
     "Preciso ficar em jejum para o ultrassom de abdome superior?",
     "Sim, em geral é preciso um jejum de alimentos antes desse exame, para a região ficar mais fácil de enxergar. Siga o tempo indicado no seu preparo e, se tiver dúvida, avise a equipe da clínica.",
     _USG),
    ("Ultrassonografia de abdome superior",
     "Posso tomar meus remédios de uso diário antes do ultrassom de abdome superior?",
     "Os remédios de uso diário costumam ser liberados com um golinho de água. Siga o seu preparo e avise a equipe da clínica sobre tudo o que você toma.",
     _USG),
    ("Ultrassonografia de abdome superior",
     "Por que pedem simeticona antes do ultrassom de abdome superior?",
     "A simeticona ajuda a reduzir os gases do intestino, que podem atrapalhar a imagem. Se ela faz parte do seu preparo, use nos momentos e nas quantidades que estão escritos nas suas orientações.",
     _USG),
    ("Ultrassonografia de abdome superior",
     "Como é o ultrassom de abdome superior e preciso de alguma roupa especial?",
     "O exame é feito com você deitado e um gel na barriga, sem agulhas. Vá com roupas confortáveis que deixem a barriga fácil de descobrir. Se algum exame anterior da região existir, leve junto.",
     _USG),

    # Ultrassonografia pélvica (bexiga cheia)
    ("Ultrassonografia pélvica (bexiga cheia)",
     "Como faço para chegar com a bexiga cheia no ultrassom pélvico?",
     "Beba líquido no tempo indicado no seu preparo, de preferência sem gás, para que a bexiga fique bem cheia no momento do exame. A bexiga cheia ajuda a enxergar melhor os órgãos da pelve.",
     _USG),
    ("Ultrassonografia pélvica (bexiga cheia)",
     "Posso fazer xixi antes do ultrassom pélvico?",
     "O ideal é segurar até o exame, pois a bexiga precisa estar suficientemente cheia. Se a vontade ficar muito forte, avise a equipe da clínica, que vai orientar você.",
     _USG),
    ("Ultrassonografia pélvica (bexiga cheia)",
     "Preciso ficar em jejum para o ultrassom pélvico?",
     "Pelo que as orientações mostram, o ponto principal desse exame é a bexiga cheia. Se o seu preparo pedir também algum jejum, siga o que está escrito nele.",
     _USG),
    ("Ultrassonografia pélvica (bexiga cheia)",
     "Levo algo para o ultrassom pélvico?",
     "Leve o pedido do exame e os ultrassons ou outros exames anteriores da região, se tiver. Isso ajuda a equipe a comparar os resultados.",
     _USG),

    # Ultrassonografia transvaginal
    ("Ultrassonografia transvaginal",
     "Preciso estar de bexiga cheia no ultrassom transvaginal?",
     "Não, nesse exame a bexiga deve estar vazia. Faça xixi antes de entrar na sala, se for possível.",
     _USG),
    ("Ultrassonografia transvaginal",
     "Posso fazer o ultrassom transvaginal menstruada?",
     "Em geral o ideal é evitar o período menstrual para realizar esse exame. Se sua menstruação descer perto da data, avise a equipe da clínica para saber como proceder.",
     _USG),
    ("Ultrassonografia transvaginal",
     "Preciso de jejum ou de algum preparo especial para o ultrassom transvaginal?",
     "Para esse exame o principal cuidado é estar com a bexiga vazia. Se o seu preparo trouxer outras orientações, siga o que está escrito.",
     _USG),
    ("Ultrassonografia transvaginal",
     "Que documentos e exames levo para o ultrassom transvaginal?",
     "Leve o pedido e os exames anteriores da região, se tiver. Se houver gravidez em investigação, avise a equipe da clínica para que ela saiba o que informar durante o exame.",
     _USG),

    # Ultrassonografia de vias urinárias e próstata
    ("Ultrassonografia de vias urinárias e próstata",
     "Preciso estar de bexiga cheia para o ultrassom de vias urinárias e próstata?",
     "Sim, a bexiga cheia é parte importante do preparo. Beba líquido pelo tempo indicado no seu preparo e evite urinar até o exame.",
     _USG),
    ("Ultrassonografia de vias urinárias e próstata",
     "Que tipo de líquido posso beber antes do ultrassom de vias urinárias?",
     "Prefira água ou outro líquido sem gás. Bebidas com gás podem atrapalhar a imagem.",
     _USG),
    ("Ultrassonografia de vias urinárias e próstata",
     "Posso tomar meus remédios antes do ultrassom de vias urinárias e próstata?",
     "Em geral os remédios de rotina podem ser tomados normalmente, com água. Siga o seu preparo e avise a equipe da clínica sobre o que você usa.",
     _USG),
    ("Ultrassonografia de vias urinárias e próstata",
     "O ultrassom de vias urinárias e próstata dói?",
     "Não costuma doer. O incômodo mais comum é a vontade de urinar por causa da bexiga cheia. Depois do exame você pode ir ao banheiro e retomar suas atividades.",
     _USG),

    # Angiotomografia
    ("Angiotomografia",
     "Preciso ficar em jejum para a angiotomografia?",
     "Sim, em geral é pedido um jejum antes da injeção do contraste na veia. Siga o tempo indicado no seu preparo e avise a equipe da clínica se tiver dúvida.",
     _ANG),
    ("Angiotomografia",
     "Uso metformina para diabetes. O que faço com ela na angiotomografia?",
     "Esse tipo de remédio costuma precisar de uma pausa combinada com quem cuida do seu tratamento, por um período que vai constar no seu preparo. Não suspenda por conta própria. Avise a equipe da clínica que você usa.",
     _ANG),
    ("Angiotomografia",
     "Tenho alergia ou problema nos rins. Posso fazer angiotomografia?",
     "Avise a equipe da clínica sobre alergia a iodo ou a contraste, asma forte ou problema nos rins antes do exame. Se o seu preparo incluir remédio antialérgico, tome nos horários indicados.",
     _ANG),
    ("Angiotomografia",
     "O que vou sentir quando injetarem o contraste na angiotomografia?",
     "É comum sentir gosto de metal na boca e uma sensação de calor pelo corpo. Isso passa rapidinho.",
     _ANG),
    ("Angiotomografia",
     "Depois da angiotomografia, quais sintomas exigem atenção?",
     "Procure atendimento se surgirem fraqueza no rosto, dormência nos braços ou pernas, perda de equilíbrio, dor no peito ou falta de ar. Se tiver alguma dúvida, avise a equipe da clínica.",
     _ANG),

    # Urotomografia
    ("Urotomografia",
     "Preciso de jejum para a urotomografia?",
     "Para adultos, a orientação encontrada é que não precisa de jejum. Siga o que estiver escrito no seu preparo, pois pode variar conforme a clínica e a idade.",
     _URO),
    ("Urotomografia",
     "Preciso beber água antes da urotomografia?",
     "Sim, é recomendado estar bem hidratado antes do exame. Beba líquidos com regularidade, conforme o seu preparo.",
     _URO),
    ("Urotomografia",
     "Que exames levo para a urotomografia?",
     "Leve o resultado recente de creatinina, que mostra como os rins estão funcionando, e exames de imagem anteriores da mesma região, se tiver feito em outro lugar.",
     _URO),
    ("Urotomografia",
     "Que roupa uso na urotomografia?",
     "Use roupa confortável e sem partes de metal, como zíper, botão ou enfeites. Roupas de algodão ou de moletom costumam ser boas.",
     _URO),
    ("Urotomografia",
     "Posso tomar meus remédios normalmente no dia da urotomografia?",
     "Em geral sim, os medicamentos de rotina seguem como de costume. Se houver alguma orientação diferente no seu preparo, siga-a.",
     _URO),
    ("Urotomografia",
     "O que devo fazer depois da urotomografia?",
     "Beba bastante líquido depois do exame, pois isso ajuda o corpo a eliminar o contraste. Retome suas atividades normalmente, a menos que a equipe da clínica indique outra coisa.",
     _URO),

    # Ressonância magnética com sedação
    ("Ressonância magnética com sedação",
     "Posso comer e beber antes da ressonância com sedação?",
     "Não, o jejum é obrigatório nesse caso, e ele tem tempos diferentes para água e para alimentos. Siga com atenção os tempos indicados no seu preparo.",
     _SED),
    ("Ressonância magnética com sedação",
     "Preciso de acompanhante na ressonância com sedação?",
     "Sim, é necessário ir com um acompanhante maior de idade. Combine com antecedência quem vai com você.",
     _SED),
    ("Ressonância magnética com sedação",
     "Posso dirigir depois da ressonância com sedação?",
     "Após uma sedação o melhor é ir e voltar com o acompanhante, sem dirigir. Pergunte à equipe da clínica quando você estará liberado para as atividades normais.",
     _SED),
    ("Ressonância magnética com sedação",
     "Que roupa e cuidados com o corpo devo ter na ressonância?",
     "Use roupa de algodão ou moletom, sem zíper ou botão. Retire objetos de metal ou magnéticos e deixe o cabelo seco, sem creme ou enfeites.",
     _SED),
    ("Ressonância magnética com sedação",
     "Preciso beber água depois da ressonância se usar contraste?",
     "Se o contraste for usado, uma boa hidratação antes e depois do exame ajuda o corpo a eliminá-lo. Siga o seu preparo sobre a forma e o momento de beber, principalmente por causa da sedação.",
     _SED),

    # Enterografia por tomografia ou ressonância
    ("Enterografia por tomografia ou ressonância",
     "Preciso ficar em jejum para a enterografia?",
     "Sim, é pedido um jejum, inclusive de líquidos, em algumas orientações. Siga o tempo e as regras do seu preparo, já que podem mudar de acordo com o serviço.",
     _ENT),
    ("Enterografia por tomografia ou ressonância",
     "Vou precisar de contraste na veia na enterografia?",
     "O contraste na veia costuma ser usado para deixar as imagens mais claras. Se você tiver alergia ou receio, avise a equipe da clínica antes do exame.",
     _ENT),
    ("Enterografia por tomografia ou ressonância",
     "Estou grávida ou com atraso menstrual. Posso fazer enterografia?",
     "Nesse caso avise a equipe da clínica antes de qualquer coisa, pois em caso de gravidez ou dúvida sobre ela o exame por tomografia não é realizado.",
     _ENT),
    ("Enterografia por tomografia ou ressonância",
     "O que levo e quando devo chegar para a enterografia?",
     "Leve o pedido do exame, documento com foto, carteirinha do convênio e CPF. Chegue com boa antecedência, conforme o horário informado na confirmação.",
     _ENT),
    ("Enterografia por tomografia ou ressonância",
     "O preparo da enterografia inclui beber algum líquido especial?",
     "Alguns serviços pedem um líquido para beber antes do exame. Se o seu preparo trouxer isso, siga as instruções e os intervalos que estão escritos.",
     _ENT),

    # Colangiorressonância
    ("Colangiorressonância",
     "Preciso de jejum para a colangiorressonância?",
     "Sim, mas em geral só para alimentos sólidos. Faça uma refeição leve na véspera e siga o tempo de jejum indicado no seu preparo.",
     _COL),
    ("Colangiorressonância",
     "Preciso beber água antes e depois da colangiorressonância?",
     "Sim, é recomendado beber bastante água antes e depois, principalmente se for usado contraste na veia. Isso ajuda o corpo a eliminá-lo.",
     _COL),
    ("Colangiorressonância",
     "Tenho marcapasso ou prótese. Posso fazer colangiorressonância?",
     "Avise a equipe da clínica antes do exame. Alguns marcapassos não são compatíveis com a ressonância, e quando são, é preciso levar a documentação que autoriza o exame.",
     _COL),
    ("Colangiorressonância",
     "O que devo tirar e que roupa uso na colangiorressonância?",
     "Retire joias, óculos, relógio, chaves e cartões magnéticos, além de cílios postiços. Use roupa sem zíper ou botão, de algodão ou moletom.",
     _COL),
    ("Colangiorressonância",
     "Posso tomar meus remédios antes da colangiorressonância?",
     "Se o seu preparo não trouxer restrição, os remédios de rotina seguem como de costume. Avise a equipe da clínica sobre tudo o que você usa.",
     _COL),
]
