# -*- coding: utf-8 -*-
"""Itens de FAQ de preparo de exames (grupo 5) para a base de conhecimento do MedIA."""

_UNIFAL = ("Laboratório Central de Análises Clínicas da FCF (UNIFAL-MG) - Preparo de exames", "https://www.unifal-mg.edu.br/lacen/preparo-de-exames/")
_CAMARA_CURVA = ("Câmara dos Deputados - Curva glicêmica simplificada", "https://www2.camara.leg.br/a-camara/estruturaadm/diretorias/diretoria-de-gestao-pessoas/preparos-de-exames/formularios/curva-glicemica-simplificada")
_CAMARA_URINA = ("Câmara dos Deputados - Preparo para exames de urina", "https://www2.camara.leg.br/a-camara/estruturaadm/diretorias/diretoria-de-gestao-pessoas/preparos-de-exames/preparo-para-exames-de-urina")
_CAMARA_FEZES = ("Câmara dos Deputados - Preparo para exames de fezes", "https://www2.camara.leg.br/a-camara/estruturaadm/diretorias/diretoria-de-gestao-pessoas/preparos-de-exames/preparo-para-exames-de-fezes")
_DOR_CALPRO = ("Rede D'Or São Luiz - Calprotectina fecal", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/calprotectina-fecal")
_MARINHA = ("Saúde Naval (Marinha do Brasil) - Orientações para espermograma", "https://www.marinha.mil.br/saudenaval/orientacoes-para-espermograma")

ITENS = [
    # ---- Curva glicêmica (TOTG) ----
    ("Curva glicêmica (TOTG)", "Preciso ficar em jejum para a curva glicêmica?",
     "Sim, você vai precisar de jejum antes da primeira coleta. O tempo exato varia conforme a idade e o laboratório, então siga o que está escrito no seu preparo. Se tiver dúvida sobre até quando pode tomar água, avise a equipe da clínica.",
     _CAMARA_CURVA),
    ("Curva glicêmica (TOTG)", "Posso mudar minha alimentação antes da curva glicêmica?",
     "O ideal é manter a sua alimentação habitual, sem cortar carboidratos de propósito nos períodos anteriores ao exame. Mudanças bruscas na dieta podem atrapalhar o resultado. Só entre em jejum no período indicado no seu preparo.",
     _CAMARA_CURVA),
    ("Curva glicêmica (TOTG)", "Posso comer ou beber alguma coisa enquanto espero entre as coletas da curva glicêmica?",
     "Não. Entre uma coleta e outra você deve ficar em repouso na clínica, sem comer nem beber nada além do que a equipe oferecer. Isso evita que o açúcar do sangue mude por outro motivo e atrapalhe a leitura.",
     _CAMARA_CURVA),
    ("Curva glicêmica (TOTG)", "Posso fazer exercício ou caminhar no dia da curva glicêmica?",
     "É melhor evitar atividade física no dia do exame e ficar em repouso durante a espera entre as coletas. O esforço pode alterar a glicose e mudar o resultado.",
     _CAMARA_CURVA),
    ("Curva glicêmica (TOTG)", "Se a minha primeira glicemia vier alterada, o teste continua?",
     "Depende do critério do laboratório. Em geral o teste só segue se o valor inicial estiver dentro do limite definido por eles. Se isso acontecer, a equipe vai explicar o que será feito na hora.",
     _CAMARA_CURVA),

    # ---- Dosagens hormonais e teste de estímulo ----
    ("Dosagens hormonais e teste de estímulo", "Preciso de jejum para dosagens hormonais como cortisol e prolactina?",
     "Muitos hormônios pedem um jejum curto, e alguns laboratórios nem exigem. Siga o tempo indicado no seu preparo, porque ele muda conforme o exame. Se tiver dúvida sobre a água, avise a equipe da clínica.",
     _UNIFAL),
    ("Dosagens hormonais e teste de estímulo", "Por que preciso coletar de manhã cedo e ficar em repouso antes de coletar?",
     "Alguns hormônios, como o cortisol, variam ao longo do dia, por isso a coleta tem horário indicado. Já a prolactina sobe com esforço e estresse, então um repouso tranquilo antes da coleta ajuda a leitura ficar fiel. Chegue com calma e sente-se um pouco antes.",
     _UNIFAL),
    ("Dosagens hormonais e teste de estímulo", "Posso fazer exercício ou ter relação sexual antes de coletar prolactina?",
     "O melhor é evitar esforço físico e atividade sexual no período antes da coleta, pelo tempo indicado no seu preparo. Também vale evitar mexer nas mamas, como em exames recentes de mama, porque isso pode alterar o valor.",
     _UNIFAL),
    ("Dosagens hormonais e teste de estímulo", "Devo tomar meus remédios de rotina antes de dosar hormônios?",
     "Em geral, você mantém os remédios de rotina, a não ser que o seu preparo diga o contrário. O importante é avisar a equipe sobre tudo o que usa, principalmente corticoides, hormônios e suplementos. Isso ajuda na leitura correta do resultado.",
     _UNIFAL),
    ("Dosagens hormonais e teste de estímulo", "Como funciona o teste de estímulo e o que vou sentir?",
     "Primeiro é feita uma coleta de sangue e depois você recebe uma substância que estimula o hormônio, seguida de novas coletas em intervalos combinados. Você fica em observação na clínica durante o teste. Se sentir qualquer mal-estar, avise a equipe na hora.",
     _UNIFAL),

    # ---- PSA ----
    ("PSA (antígeno prostático)", "Preciso de jejum para o exame de PSA?",
     "Alguns laboratórios pedem um jejum curto e outros não exigem nenhum. Siga o tempo indicado no seu preparo. Se a orientação não estiver clara, pergunte à equipe da clínica.",
     _UNIFAL),
    ("PSA (antígeno prostático)", "Ejacular antes do PSA atrapalha o exame?",
     "Atrapalha sim, porque a ejaculação pode elevar o PSA por um tempo. Por isso o preparo pede um intervalo sem ejacular antes da coleta. Respeite o tempo que está no seu preparo.",
     _UNIFAL),
    ("PSA (antígeno prostático)", "Posso andar de bicicleta ou moto antes de coletar o PSA?",
     "O ideal é evitar bicicleta, moto e cavalgada no período indicado no seu preparo, pois o atrito na região da próstata pode alterar o valor. Esforço físico intenso também entra na lista do que evitar.",
     _UNIFAL),
    ("PSA (antígeno prostático)", "Fiz exame de toque ou outro procedimento na próstata, posso coletar o PSA agora?",
     "Exame de toque, sondagem, ultrassom transretal, colonoscopia e biópsia podem mexer no valor do PSA. Cada um pede um intervalo diferente antes da coleta. Avise a equipe da clínica sobre o que você fez e siga o preparo.",
     _UNIFAL),
    ("PSA (antígeno prostático)", "Posso tomar meus remédios normalmente no dia do PSA?",
     "Em geral sim, a menos que o seu preparo diga algo diferente. Avise a equipe sobre todos os remédios que você usa, principalmente os relacionados à próstata.",
     _UNIFAL),

    # ---- Coleta de urina de 24 horas ----
    ("Coleta de urina de 24 horas", "Como começo a coleta de urina do dia inteiro?",
     "Você começa em um horário de manhã, esvaziando a bexiga no vaso e descartando essa primeira urina. A partir daí, guarde toda a urina no frasco. Anote o horário em que começou, porque ele será a referência para o final.",
     _UNIFAL),
    ("Coleta de urina de 24 horas", "Onde guardo o frasco da coleta de urina do dia inteiro?",
     "Mantenha o frasco bem fechado e conservado na geladeira entre as micções, sem congelar. Ao urinar, você pode usar um recipiente limpo e passar o conteúdo para o frasco. Deixe o frasco longe de crianças e de alimentos.",
     _UNIFAL),
    ("Coleta de urina de 24 horas", "Esqueci de guardar uma urina durante a coleta, e agora?",
     "Avise a equipe da clínica o quanto antes e conte o que aconteceu. Como o exame depende de toda a urina do período, uma perda pode mudar o resultado. Eles vão orientar se é preciso repetir a coleta.",
     _UNIFAL),
    ("Coleta de urina de 24 horas", "Como termino a coleta de urina do dia inteiro?",
     "No fim, você recolhe a urina da manhã seguinte, no mesmo horário em que descartou a primeira. Essa última amostra entra no frasco. Depois leve tudo ao laboratório conforme o prazo do seu preparo.",
     _UNIFAL),
    ("Coleta de urina de 24 horas", "Preciso mudar minha alimentação ou beber menos água durante a coleta?",
     "Em geral você mantém a rotina e continua se hidratando normalmente, salvo orientação diferente no seu preparo. Em alguns exames específicos pode haver restrições a certos alimentos. Nesse caso, siga o que está no seu preparo.",
     _UNIFAL),

    # ---- Urina tipo 1 e urocultura ----
    ("Urina tipo 1 e urocultura", "Qual é a melhor urina para coletar, a da manhã?",
     "Em geral, a primeira urina da manhã é a preferida. Se não der, colha com o intervalo mínimo indicado no seu preparo desde a última vez que urinou. Isso deixa a amostra mais concentrada e confiável.",
     _CAMARA_URINA),
    ("Urina tipo 1 e urocultura", "Como faço a higiene antes de coletar a urina?",
     "Lave bem a região genital com água e sabão e enxágue bem. Não use antissépticos, a menos que o seu preparo peça. A higiene ajuda a evitar contaminação da amostra.",
     _CAMARA_URINA),
    ("Urina tipo 1 e urocultura", "O que é o jato médio e como faço isso?",
     "Você descarta o primeiro jato no vaso, coleta o jato do meio no frasco e finaliza no vaso. Não encoste o frasco no corpo nem toque na parte de dentro. Esse cuidado evita que bactérias da pele apareçam no exame.",
     _CAMARA_URINA),
    ("Urina tipo 1 e urocultura", "Como guardo e levo a amostra de urina até o laboratório?",
     "Feche bem o frasco e leve logo ao laboratório, dentro do prazo do seu preparo. Para a urocultura, costuma-se transportar o frasco em uma vasilha com gelo. Se atrasar, avise a equipe.",
     _CAMARA_URINA),
    ("Urina tipo 1 e urocultura", "Estou usando antibiótico ou estou menstruada, posso coletar a urina?",
     "Avise a equipe da clínica se usa ou usou antibiótico ou antisséptico urinário, pois isso pode mudar o resultado da urocultura. Na menstruação, procure orientação da equipe sobre como coletar, já que o sangue pode contaminar a amostra.",
     _CAMARA_URINA),

    # ---- Parasitológico de fezes ----
    ("Parasitológico de fezes", "Como coleto as fezes para o parasitológico?",
     "Use o frasco fornecido pelo laboratório, que normalmente já vem com líquido conservante. Coloque a quantidade indicada com a espátula e evite encher o frasco por completo. As fezes precisam ficar cobertas pelo líquido.",
     _CAMARA_FEZES),
    ("Parasitológico de fezes", "Preciso levar mais de uma amostra de fezes?",
     "Isso depende do pedido. Alguns exames pedem uma amostra e outros pedem várias coletas em momentos diferentes. Siga a quantidade que está no seu preparo, porque isso aumenta a chance de encontrar o parasita.",
     _CAMARA_FEZES),
    ("Parasitológico de fezes", "Preciso guardar as fezes na geladeira?",
     "Quando o frasco tem conservante, em geral não precisa de geladeira. Se a coleta for sem conservante, o laboratório pode pedir refrigeração até a entrega. Siga o prazo e a conduta descritos no seu preparo.",
     _CAMARA_FEZES),
    ("Parasitológico de fezes", "Posso coletar as fezes se elas ficaram misturadas com urina ou água do vaso?",
     "O ideal é evitar. Faça a coleta em um recipiente limpo e seco, como um pinico ou um plástico sobre o vaso, para não misturar com urina ou água. Se isso aconteceu, avise a equipe para ver se é melhor repetir.",
     _CAMARA_FEZES),
    ("Parasitológico de fezes", "Posso usar laxante para conseguir coletar?",
     "Evite por conta própria, porque laxantes e alguns produtos podem atrapalhar a leitura da amostra. Se você tem intestino preso, avise a equipe da clínica. Eles vão indicar a melhor forma de coletar.",
     _UNIFAL),

    # ---- Pesquisa de sangue oculto e calprotectina fecal ----
    ("Pesquisa de sangue oculto e calprotectina fecal", "Posso fazer a coleta durante a menstruação?",
     "É melhor evitar. O sangue da menstruação pode contaminar a amostra e alterar o resultado. Espere terminar o período menstrual antes de coletar, ou avise a equipe se isso não for possível.",
     _CAMARA_FEZES),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Posso tomar anti-inflamatório ou vitamina C antes de coletar as fezes?",
     "Anti-inflamatórios, analgésicos e vitamina C podem interferir na pesquisa de sangue oculto. Avise a equipe sobre tudo o que você toma, inclusive suplementos, e siga o seu preparo sobre o que suspender ou não.",
     _UNIFAL),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Preciso mudar a alimentação antes do exame de sangue oculto?",
     "Alguns laboratórios não pedem restrição alimentar hoje, mas outros ainda pedem. Siga o que está no seu preparo. Se não houver orientação, mantenha a alimentação habitual.",
     _UNIFAL),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Como coleto as fezes para a calprotectina fecal?",
     "Use o frasco do laboratório e a espátula que vem nele, colocando só uma pequena quantidade até a marca indicada. Evite contato com água do vaso e com urina. Feche bem o frasco e entregue o quanto antes, dentro do prazo do seu preparo.",
     _DOR_CALPRO),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Fiz colonoscopia ou usei laxante recentemente, posso coletar a calprotectina?",
     "Laxantes, preparos intestinais e procedimentos como a colonoscopia podem interferir no exame. O laboratório costuma pedir um intervalo antes da coleta, que está no seu preparo. Avise a equipe sobre o que você fez.",
     _DOR_CALPRO),

    # ---- Espermograma ----
    ("Espermograma", "Preciso de jejum ou de algum cuidado com alimentação para o espermograma?",
     "Não é necessário jejum para o espermograma. Mantenha a alimentação normal e beba água como de costume. O cuidado principal é com a abstinência sexual antes da coleta.",
     _MARINHA),
    ("Espermograma", "Quanto tempo de abstinência sexual devo cumprir antes do espermograma?",
     "É preciso ficar sem ejacular, seja por relação ou masturbação, pelo período indicado no seu preparo. Nem menos nem mais do que o combinado, porque isso muda o resultado. Se errou a contagem, avise a equipe antes de coletar.",
     _MARINHA),
    ("Espermograma", "Como devo coletar a amostra do espermograma?",
     "A coleta é por masturbação, direto no frasco fornecido pelo laboratório, mantendo o frasco aberto durante a coleta. Não use saliva, lubrificantes nem preservativo comum. Anote o horário da coleta e preencha o questionário que acompanha o frasco.",
     _MARINHA),
    ("Espermograma", "Posso coletar em casa e levar a amostra depois?",
     "Isso depende do laboratório. Em alguns locais a coleta só é aceita na própria unidade. Se puder levar de casa, siga rigorosamente as regras de transporte do seu preparo.",
     _MARINHA),
    ("Espermograma", "Perdi parte da amostra durante a coleta, o que faço?",
     "Avise a equipe logo em seguida e informe que houve perda, porque o resultado pode ficar incorreto. Em geral será preciso repetir a coleta depois de cumprir de novo a abstinência do seu preparo. Não tente completar a amostra depois.",
     _MARINHA),
]
