# -*- coding: utf-8 -*-
"""Itens adicionais de FAQ de preparo (grupo 11)."""

ITENS = [
    # ===== Ressonância magnética com sedação =====
    ("Ressonância magnética com sedação", "Quem costuma precisar de sedação para fazer ressonância?", "A sedação costuma ser usada quando a pessoa tem dificuldade para ficar parada, como bebês e crianças pequenas, quem sente muita ansiedade ou claustrofobia, ou quem sente dores que impedem de manter a posição. A equipe avalia cada caso. Ela só é feita com pedido e acompanhamento de anestesista.", ("Telemedicina Morsch - Ressonância magnética com sedação", "https://telemedicinamorsch.com.br/blog/ressonancia-magnetica-com-sedacao")),
    ("Ressonância magnética com sedação", "Qual a diferença entre sedação leve e anestesia geral na ressonância?", "Na sedação leve você fica sonolento, mas continua consciente e responde a comandos simples. Na anestesia geral você dorme profundamente durante todo o exame. Em ambos os casos um anestesista acompanha você do começo ao fim.", ("Blumé Diagnósticos - Sedação na ressonância magnética", "https://blumediagnosticos.com.br/sedacao-na-ressonancia-magnetica-quando-e-indicada-e-como-funciona/")),
    ("Ressonância magnética com sedação", "Vou conversar com o anestesista antes do exame?", "Sim, costuma haver uma avaliação antes da sedação, em que o anestesista olha suas condições de saúde e os remédios que você usa e esclarece suas dúvidas. Aproveite para contar tudo o que for importante sobre você. Alguns locais pedem exames prévios, como o eletrocardiograma.", ("SAJ - Anestesia para ressonância magnética", "https://saj.med.br/entenda-como-e-feita-a-anestesia-para-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "Preciso levar a lista dos remédios que uso para a sedação?", "É uma boa ideia. Leve o nome dos medicamentos, das vitaminas e dos suplementos que você usa para o anestesista avaliar com calma. Se você usa bombinha para asma ou bronquite, avise e leve com você.", ("Telemedicina Morsch - Ressonância magnética com sedação", "https://telemedicinamorsch.com.br/blog/ressonancia-magnetica-com-sedacao")),
    ("Ressonância magnética com sedação", "Como a equipe me acompanha enquanto estou sedado?", "Durante todo o exame você é monitorado por aparelhos que acompanham o coração, a respiração, a oxigenação e a pressão arterial. Uma equipe com anestesista e radiologista fica atenta o tempo todo. Por isso é importante seguir o jejum do seu preparo.", ("HAS - Ressonância magnética com sedação", "https://hasabin.com.br/ressonancia-magnetica-com-sedacao/")),
    ("Ressonância magnética com sedação", "A ressonância com sedação dói?", "O exame em si não causa dor. O que você pode sentir é apenas a picada do acesso na veia, quando ele é necessário. Depois disso, a sedação faz você ficar tranquilo ou dormindo até o fim.", ("HAS - Ressonância magnética com sedação", "https://hasabin.com.br/ressonancia-magnetica-com-sedacao/")),
    ("Ressonância magnética com sedação", "O que acontece se eu não cumprir o jejum da sedação?", "O jejum protege você, porque com o estômago cheio existe o risco de o conteúdo voltar e atingir os pulmões. Por isso, se ele não for cumprido, a sedação e o exame podem ser cancelados. Se tiver qualquer dúvida sobre ter comido ou bebido, avise a equipe assim que chegar.", ("SAJ - Anestesia para ressonância magnética", "https://saj.med.br/entenda-como-e-feita-a-anestesia-para-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "Depois do exame, para onde vou e quando posso ir embora?", "Ao acordar, você segue para uma sala de recuperação, onde a equipe acompanha seus sinais até você estar em condições de sair. O anestesista avalia você antes da alta e passa as orientações finais. Seu acompanhante deve estar por perto nesse momento.", ("Clínica IMR - Sedação para ressonância magnética", "https://clinicaimr.com.br/quando-e-como-e-feita-a-sedacao-para-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "É normal sentir sono, enjoo ou tontura depois da sedação?", "Sim, sonolência, enjoo, tontura, dor de cabeça e desconforto no corpo são reações leves e mais comuns. Se algo parecer forte ou não melhorar, avise a equipe da clínica ainda no local. Reflexos e atenção podem ficar alterados, então evite tarefas que exijam concentração.", ("Telemedicina Morsch - Ressonância magnética com sedação", "https://telemedicinamorsch.com.br/blog/ressonancia-magnetica-com-sedacao")),
    ("Ressonância magnética com sedação", "Tenho asma, bronquite ou alergia a contraste. Preciso de algum preparo?", "Sim, pessoas com alergia importante costumam precisar de um preparo antialérgico específico, e a ausência dele pode levar ao reagendamento. Avise a equipe ao marcar o exame e siga o preparo que receber. Quem usa remédio broncodilatador deve levá-lo no dia.", ("AME Votuporanga - Preparo de ressonância com sedação", "https://amevotuporanga.com.br/preparos-exames/587390b73a01a0fd07151cdc4cbe1ad9.pdf")),
    ("Ressonância magnética com sedação", "Estou gripado ou tomei vacina recentemente. Posso fazer o exame com sedação?", "Sintomas de gripe e vacinação recente podem impedir a sedação, então avise a equipe antes de ir. Ela vai orientar se o exame precisa ser remarcado. O melhor é chegar bem para que a sedação seja segura.", ("AME Votuporanga - Preparo de ressonância com sedação", "https://amevotuporanga.com.br/preparos-exames/587390b73a01a0fd07151cdc4cbe1ad9.pdf")),
    ("Ressonância magnética com sedação", "Tenho marcapasso, clipe de aneurisma ou stent. Posso fazer?", "Esses dispositivos podem impedir a ressonância ou exigir documentos que comprovem a compatibilidade. Informe a equipe ao agendar e leve o cartão do implante, se tiver. Aparelho ortodôntico fixo e tatuagens grandes também precisam ser avisados.", ("AME Votuporanga - Preparo de ressonância com sedação", "https://amevotuporanga.com.br/preparos-exames/587390b73a01a0fd07151cdc4cbe1ad9.pdf")),
    ("Ressonância magnética com sedação", "Existe limite de peso para fazer a ressonância com sedação?", "Sim, o equipamento e o protocolo de sedação têm um limite de peso definido por cada serviço. Informe seu peso ao marcar o exame para evitar surpresas no dia. A equipe vai orientar se for preciso outra opção.", ("AME Votuporanga - Preparo de ressonância com sedação", "https://amevotuporanga.com.br/preparos-exames/587390b73a01a0fd07151cdc4cbe1ad9.pdf")),
    ("Ressonância magnética com sedação", "Estou amamentando e vou usar contraste com sedação. Como fica o leite?", "Se o exame usar contraste, algumas clínicas orientam um período sem amamentar depois e sugerem deixar leite coletado antes. Esse tempo é definido por cada serviço e consta no seu preparo. Avise a equipe que você amamenta para receber a orientação certa.", ("AME Votuporanga - Preparo de ressonância com sedação", "https://amevotuporanga.com.br/preparos-exames/587390b73a01a0fd07151cdc4cbe1ad9.pdf")),
    ("Ressonância magnética com sedação", "Posso trabalhar ou fazer minhas atividades no dia do exame com sedação?", "O ideal é reservar o dia para descansar, porque a sedação pode alterar seus reflexos e sua atenção. Evite trabalhar, operar máquinas ou tomar decisões importantes até se sentir totalmente recuperado. Combine com antecedência para não ter compromissos nesse período.", ("SAJ - Anestesia para ressonância magnética", "https://saj.med.br/entenda-como-e-feita-a-anestesia-para-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "Tenho claustrofobia. A sedação resolve o incômodo do aparelho?", "A sedação ajuda bastante, pois você fica tranquilo ou dormindo enquanto o exame é feito. Alguns locais também oferecem aparelhos de abertura maior. Avise a equipe sobre a claustrofobia ao marcar para que o exame seja planejado com sedação.", ("Le Forte - O que precisa para fazer ressonância magnética", "https://www.leforte.com.br/blog/o-que-precisa-para-fazer-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "Como preparo meu filho pequeno para a ressonância com sedação?", "Explique de forma simples que a máquina tira fotos por dentro do corpo e não dói, e mantenha a calma, pois as crianças percebem a ansiedade dos pais. Siga direitinho o jejum indicado no preparo e vista roupa confortável sem metal. Leve os documentos e avise sobre alergias.", ("Casa da Esperança - Ressonância magnética em criança", "https://casadaesperanca.com.br/ressonancia-magnetica-em-crianca/")),
    ("Ressonância magnética com sedação", "Como cuidar da criança depois da ressonância com sedação?", "A criança é observada até acordar por completo. Depois, é normal ela ficar sonolenta ou irritada, e a coordenação pode estar um pouco alterada. Não deixe a criança sozinha e mantenha o cuidado de perto no restante do dia.", ("Casa da Esperança - Ressonância magnética em criança", "https://casadaesperanca.com.br/ressonancia-magnetica-em-crianca/")),
    ("Ressonância magnética com sedação", "O tempo total na clínica é maior por causa da sedação?", "Sim, além do exame em si você passa pelo preparo com a equipe e pela recuperação depois. Também pode haver atraso por causa da coordenação com o anestesista. Programe-se para ficar mais tempo na unidade do que em uma ressonância comum.", ("CDI Clínica de Imagem - Preparo de ressonância magnética", "https://cdi.med.br/preparo-ressonancia-magnetica/")),
    ("Ressonância magnética com sedação", "Preciso fazer exames antes de ser sedado?", "Alguns serviços pedem exames prévios, como eletrocardiograma e exames de sangue, para o anestesista avaliar sua segurança. Isso costuma constar nas orientações de agendamento. Se você não receber essa informação, pergunte à equipe ao marcar.", ("HAS - Ressonância magnética com sedação", "https://hasabin.com.br/ressonancia-magnetica-com-sedacao/")),
    ("Ressonância magnética com sedação", "A sedação tem riscos?", "Como em qualquer sedação ou anestesia, existem riscos raros, principalmente respiratórios, cardiovasculares ou alérgicos, e por isso você é monitorado o tempo todo. Reações leves, como enjoo e tontura, são mais comuns. Seguir o jejum e avisar sobre alergias e remédios reduz esses riscos.", ("Telemedicina Morsch - Ressonância magnética com sedação", "https://telemedicinamorsch.com.br/blog/ressonancia-magnetica-com-sedacao")),
