# -*- coding: utf-8 -*-
"""Itens adicionais de FAQ de preparo (grupo 12)."""

_SL = "Rede D'Or São Luiz"
_SL_UE = (_SL, "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-urografia-excretora")
_XL = ("X-LEME Diagnóstico por Imagem", "https://www.xleme.com.br/preparos-urografia-excretora.html")
_ABC = ("AbcMed", "https://abc.med.br/exames-e-procedimentos/urografia-excretora-como-e-este-exame")
_DG = ("Diagmed", "https://diagmed.com.br/exames/raio-x-urografia-excretora/")
_EI = ("Eigier Diagnósticos", "https://eigierdiagnosticos.com.br/blog/urografia-excretora/")
_TS_UE = ("Tua Saúde", "https://www.tuasaude.com/en/intravenous-pyelogram/")

ITENS = [
    # ---------------- Urografia excretora ----------------
    ("Urografia excretora", "O que vou sentir quando injetarem o contraste na veia?",
     "É comum sentir calor pelo corpo, gosto metálico na boca e, às vezes, enjoo ou vontade de vomitar. Costuma passar rápido. Se algo incomodar muito, avise logo a equipe.",
     _ABC),
    ("Urografia excretora", "Uso remédio para diabetes com metformina. Preciso avisar antes da urografia excretora?",
     "Sim, avise a equipe no agendamento. Esse remédio costuma exigir uma pausa antes e depois do exame, pelo tempo indicado no seu preparo. Siga exatamente o que a unidade orientar.",
     _XL),
    ("Urografia excretora", "Como é feita a urografia excretora, passo a passo?",
     "Você deita na mesa e são feitas algumas imagens antes do contraste. Depois o contraste entra pela veia do braço e novas imagens são feitas em intervalos, acompanhando o caminho do contraste pelos rins, ureteres e bexiga.",
     _ABC),
    ("Urografia excretora", "A urografia excretora demora muito?",
     "O tempo é moderado, mas pode se prolongar conforme a rapidez com que seus rins eliminam o contraste. Vá sem pressa e sem outros compromissos logo em seguida.",
     _SL_UE),
    ("Urografia excretora", "O que devo levar para a urografia excretora?",
     "Leve o pedido médico, documento com foto, carteirinha do convênio e exames de imagem anteriores. Se você tem problema nos rins, leve também o exame de função renal recente.",
     _SL_UE),
    ("Urografia excretora", "Posso ir de joias, óculos e dentadura móvel para a urografia excretora?",
     "O ideal é deixar em casa ou retirar antes das imagens joias, óculos, aparelhos dentários móveis e qualquer objeto de metal. Evite também roupas com zíper ou fivelas na região da barriga.",
     _EI),
    ("Urografia excretora", "Preciso beber água depois da urografia excretora?",
     "Sim, em geral é recomendado se hidratar bem depois do exame para ajudar o corpo a eliminar o contraste mais rápido. Siga a orientação da unidade se você tiver alguma restrição de líquidos.",
     _ABC),
    ("Urografia excretora", "Apareceu coceira ou manchas na pele depois da urografia excretora. O que faço?",
     "Coceira, manchas ou inchaço podem ser sinais de reação ao contraste. Avise imediatamente a equipe se ainda estiver na unidade. Se falta de ar ou inchaço na garganta aparecerem, procure atendimento de urgência.",
     _EI),
    ("Urografia excretora", "Vão me pedir para urinar no meio da urografia excretora?",
     "Pode ser que sim. Perto do fim do exame às vezes se pede que você esvazie a bexiga para uma imagem adicional. A equipe avisa na hora.",
     _EI),
    ("Urografia excretora", "Preciso ficar parado durante as imagens da urografia excretora?",
     "Sim, ficar quieto ajuda a deixar as imagens nítidas. Você também pode ser chamado a mudar de posição e a segurar a respiração por instantes, sempre com orientação do técnico.",
     _EI),
    ("Urografia excretora", "Tenho um problema nos rins ou só um rim. Isso muda algo para a urografia excretora?",
     "Avise a equipe ao agendar. Nesses casos costuma ser pedido um exame de função dos rins recente e o exame pode demorar mais, porque depende da eliminação do contraste.",
     _SL_UE),
    ("Urografia excretora", "Meu filho vai fazer a urografia excretora. Como funciona o jejum e o acompanhante?",
     "O tempo de jejum para crianças é menor e varia conforme a idade, por isso siga o preparo entregue pela unidade. Menores de idade precisam de um responsável adulto durante o exame.",
     _SL_UE),
    ("Urografia excretora", "Estou com atraso menstrual. Posso fazer a urografia excretora?",
     "Se houver gravidez, suspeita ou dúvida, atraso menstrual incluído, o exame não deve ser feito por causa da radiação. Avise a equipe no agendamento para reorganizar a data.",
     _SL_UE),
    ("Urografia excretora", "Preciso chegar mais cedo para a urografia excretora?",
     "Sim, é recomendado chegar com antecedência ao horário marcado para fazer o cadastro e responder ao questionário da equipe. Em alguns locais o exame precisa ser agendado pessoalmente.",
     _XL),
    ("Urografia excretora", "Quem me passa o resultado da urografia excretora?",
     "As imagens são analisadas por um radiologista, que emite o laudo. Em geral ele é entregue à parte, conforme o prazo da unidade, e a interpretação fica com o profissional que pediu o exame.",
     _EI),
    ("Urografia excretora", "Tenho dificuldade de ficar parado. Existe algum recurso para a urografia excretora?",
     "Em casos de dificuldade para ficar imóvel, a sedação pode ser considerada em alguns serviços. Avise a equipe no agendamento para que combinem a melhor forma de fazer o exame.",
     _TS_UE),

    # ---------------- Uretrocistografia miccional ----------------
    ("Uretrocistografia miccional", "Preciso de jejum ou dieta especial para a uretrocistografia miccional?",
     "Depende da unidade. Algumas não exigem jejum e outras pedem uma dieta líquida leve ou um jejum curto. Siga o preparo que você recebeu no agendamento.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "A colocação da sonda dói na uretrocistografia miccional?",
     "O exame não costuma ser doloroso, mas pode haver um desconforto leve na passagem da sonda e na hora de urinar com o contraste. Em geral é rápido.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "Vão usar anestesia na uretrocistografia miccional?",
     "Em muitos serviços é aplicado um anestésico local na região para reduzir o incômodo da passagem da sonda. Pergunte à equipe como será no seu caso.",
     ("Tua Saúde", "https://www.tuasaude.com/uretrocistografia/")),
    ("Uretrocistografia miccional", "Como é feita a uretrocistografia miccional, passo a passo?",
     "Você deita na mesa, a região é higienizada e uma sonda fina leva o contraste até a bexiga. São feitas imagens enquanto ela enche e depois você urina, para observar o caminho do contraste. No fim a sonda é retirada.",
     ("Crya", "https://crya.com.br/seo/uretrocistografia-adulta-procedimento-indicacoes-e-preparacao/")),
    ("Uretrocistografia miccional", "Vou precisar urinar deitado durante a uretrocistografia miccional?",
     "Sim, faz parte do exame. Você urina na própria mesa, com a equipe organizando toalhas ou recipiente. É normal ter vergonha, mas é uma etapa de rotina para eles.",
     ("Dr. Anselmo Hoffmann", "https://dranselmohoffmann.com.br/uretrocistografia-miccional-retrograda-cum/")),
    ("Uretrocistografia miccional", "Quanto tempo dura a uretrocistografia miccional?",
     "Em geral é um exame de duração moderada, que pode se estender conforme a função dos rins e o tempo que a bexiga leva para esvaziar. Reserve a manhã ou a tarde sem outros compromissos.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "Estou com sintomas de infecção urinária. Posso fazer a uretrocistografia miccional?",
     "Avise a equipe antes, porque o exame não deve ser feito se houver suspeita ou confirmação de infecção urinária. Ele costuma ser remarcado para depois do tratamento.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "Posso fazer a uretrocistografia miccional se estiver grávida ou com atraso menstrual?",
     "Se houver gravidez, suspeita ou dúvida, o exame precisa ser avaliado antes por causa da radiação. Avise a equipe no agendamento para que orientem a melhor conduta.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "O que é normal e o que não é depois da uretrocistografia miccional?",
     "É comum ter uma leve ardência nas primeiras vezes que urinar e a urina ficar meio rosada. Beba bastante líquido para ajudar. Avise a equipe ou procure atendimento se surgirem dor, febre ou sangue na urina.",
     ("Dr. Anselmo Hoffmann", "https://dranselmohoffmann.com.br/uretrocistografia-miccional-retrograda-cum/")),
    ("Uretrocistografia miccional", "Tenho alergia a iodo ou látex. Preciso avisar antes da uretrocistografia miccional?",
     "Sim. O contraste tem iodo e a sonda pode ter materiais que causam reação em algumas pessoas. Conte à equipe sobre qualquer alergia, inclusive a medicamentos.",
     ("Tua Saúde", "https://www.tuasaude.com/uretrocistografia/")),
    ("Uretrocistografia miccional", "Uso remédio para diabetes ou anticoagulante. Preciso informar na uretrocistografia miccional?",
     "Sim, informe todos os remédios em uso, principalmente os de diabetes e os anticoagulantes, para que a equipe oriente o que fazer no seu preparo. Não pare nenhum por conta própria.",
     ("Tua Saúde", "https://www.tuasaude.com/uretrocistografia/")),
    ("Uretrocistografia miccional", "Meu filho vai fazer a uretrocistografia miccional. Como preparo a criança?",
     "Explique com calma e linguagem simples o que vai acontecer, inclusive que ele vai urinar na mesa. Levar chupeta, cobertor ou brinquedo ajuda. Um adulto precisa acompanhar, e em alguns casos a equipe pode indicar sedação.",
     ("Dr. Anselmo Hoffmann", "https://dranselmohoffmann.com.br/uretrocistografia-miccional-retrograda-cum/")),
    ("Uretrocistografia miccional", "Devo levar exames de urina para a uretrocistografia miccional?",
     "Algumas unidades pedem exame de urina ou urocultura recente e checam se há sinais de infecção antes de começar. Leve também exames de imagem anteriores relacionados ao problema.",
     ("FIDI", "https://fidi.org.br/docs/exames/preparos/raio-x/adulto/preparo_para_exame_de_radiografia_contrastada_uretrocistografia_miccional_e_retrograda_adulto.pdf?_t=1711626836")),
    ("Uretrocistografia miccional", "Posso voltar às minhas atividades depois da uretrocistografia miccional?",
     "Em geral sim, você pode retomar a rotina logo depois, a menos que a equipe oriente diferente. Beba água e urine com frequência para eliminar o contraste.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "Posso levar meu filho pequeno como acompanhante na uretrocistografia miccional?",
     "Não é indicado. A unidade costuma não ter equipe para cuidar de crianças durante o exame de outra pessoa. Se possível, deixe-as com alguém e venha com um acompanhante adulto.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/raio-x-uretrocistografia-miccional-adulto")),
    ("Uretrocistografia miccional", "Posso ir com joias e roupas com metal para a uretrocistografia miccional?",
     "Retire joias e acessórios de metal e use roupas fáceis de tirar. Você provavelmente vai trocar por uma roupa da unidade.",
     ("Tua Saúde", "https://www.tuasaude.com/uretrocistografia/")),

    # ---------------- Histerossalpingografia ----------------
    ("Histerossalpingografia", "A histerossalpingografia dói?",
     "Costuma causar um desconforto parecido com cólica menstrual, com sensação de pressão, que passa logo depois do exame. A intensidade varia de pessoa para pessoa e, para a maioria, é tolerável.",
     ("Flávia Starling", "https://flaviastarling.com.br/blog/histerossalpingografia-o-que-e-quando-e-indicada/")),
    ("Histerossalpingografia", "Posso tomar remédio para cólica antes da histerossalpingografia?",
     "Algumas unidades orientam tomar um antiespasmódico ou analgésico antes para reduzir o desconforto. Siga o que estiver no seu preparo e leve o que costuma usar para a dor, caso a equipe permita.",
     ("Mater Prime", "https://materprime.com.br/histerossalpingografia-hsg/")),
    ("Histerossalpingografia", "Quanto tempo dura a histerossalpingografia?",
     "O exame em si é curto, e o tempo total na unidade é de algo em torno de uma consulta rápida. A duração varia conforme o serviço, então reserve o período sem outros compromissos.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/histerossalpingografia")),
    ("Histerossalpingografia", "Estou com sangramento vaginal no dia marcado. Posso fazer a histerossalpingografia?",
     "Avise a equipe. Sangramento vaginal no momento é um motivo para não realizar o exame naquele dia, e ele costuma ser remarcado dentro da fase correta do ciclo.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/histerossalpingografia")),
    ("Histerossalpingografia", "Estou com corrimento ou infecção. Posso fazer a histerossalpingografia?",
     "Avise antes. Com corrimento ou infecção genital ativa o exame geralmente não é feito, para evitar complicações. Ele será remarcado quando você estiver liberada.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/histerossalpingografia")),
    ("Histerossalpingografia", "Preciso fazer teste de gravidez antes da histerossalpingografia?",
     "Algumas unidades exigem um exame de gravidez recente no dia do procedimento, e sem ele o exame não é feito. O exame não deve ser realizado se houver gravidez ou suspeita, por causa da radiação.",
     ("Ecomax", "https://ecomax-cdi.com.br/Preparos/RX/RX-PREPARO_PARA_HISTEROSSALPINGOGRAFIA.pdf")),
    ("Histerossalpingografia", "O que levar para a histerossalpingografia?",
     "Leve pedido médico original, documento com foto, carteirinha do convênio, exames pélvicos anteriores e, se a unidade pedir, o termo de consentimento assinado e o resultado do teste de gravidez.",
     ("Ecomax", "https://ecomax-cdi.com.br/Preparos/RX/RX-PREPARO_PARA_HISTEROSSALPINGOGRAFIA.pdf")),
    ("Histerossalpingografia", "Que roupa e o que mais devo levar para ficar confortável na histerossalpingografia?",
     "Vá com roupa leve e confortável e leve um absorvente, pois pode haver cólica e um pequeno sangramento depois. Também vale planejar um período de descanso após o exame.",
     ("Omni Diagnóstico", "https://omnidiag.com.br/histerossalpingografia/")),
    ("Histerossalpingografia", "Posso fazer depilação antes da histerossalpingografia?",
     "Alguns serviços pedem para evitar depilar a região logo antes, pois a pele pode ficar mais sensível. Siga o seu preparo e, na dúvida, pergunte à equipe.",
     ("Omni Diagnóstico", "https://omnidiag.com.br/histerossalpingografia/")),
    ("Histerossalpingografia", "É normal sangrar depois da histerossalpingografia?",
     "Um pequeno sangramento e uma cólica leve são esperados. Procure atendimento se houver sangramento intenso, febre, dor forte, enjoo ou vômitos, pois podem indicar necessidade de avaliação.",
     ("Mater Prime", "https://materprime.com.br/histerossalpingografia-hsg/")),
    ("Histerossalpingografia", "Posso voltar ao trabalho depois da histerossalpingografia?",
     "Na maioria dos casos você retoma as atividades normais no mesmo dia, mas pode sentir um leve desconforto pélvico por um tempo. Se puder, planeje uma rotina mais tranquila.",
     ("Mater Prime", "https://materprime.com.br/histerossalpingografia-hsg/")),
    ("Histerossalpingografia", "Quando posso ter relações sexuais depois da histerossalpingografia?",
     "Em geral, orienta-se esperar até parar qualquer sangramento leve e seguir o prazo que a equipe informar para o seu caso.",
     ("Omni Diagnóstico", "https://omnidiag.com.br/histerossalpingografia/")),
    ("Histerossalpingografia", "Tenho alergia a contraste com iodo. Posso fazer a histerossalpingografia?",
     "Avise a equipe antes. O histórico de alergia ao contraste iodado precisa ser avaliado pelo radiologista, que decidirá como proceder.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/histerossalpingografia")),
    ("Histerossalpingografia", "Tenho medo ou vaginismo. Existe alguma opção para a histerossalpingografia?",
     "Avise a equipe ao agendar. Nesses casos pode ser indicada sedação ou outro cuidado para deixar o exame mais confortável. Você não precisa enfrentar sozinha.",
     ("Rede D'Or São Luiz", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/raio-x-contrastado/histerossalpingografia")),
    ("Histerossalpingografia", "Como sai o resultado da histerossalpingografia?",
     "O laudo mostra se as tubas estão abertas ou obstruídas e como está a cavidade do útero. Fica pronto conforme o prazo da unidade, e quem pediu o exame explica o que fazer.",
     ("Mater Prime", "https://materprime.com.br/histerossalpingografia-hsg/")),
    ("Histerossalpingografia", "Preciso me alimentar de forma especial antes da histerossalpingografia?",
     "Algumas unidades pedem comer leve antes e um laxante suave na véspera. Siga o preparo da sua unidade, pois ele varia.",
     ("Mater Prime", "https://materprime.com.br/histerossalpingografia-hsg/")),
