# -*- coding: utf-8 -*-
"""Itens adicionais de FAQ de preparo (grupo 9)."""

ITENS = [
    # ---------------- Teste respiratório da ureia (H. pylori) ----------------
    ("Teste respiratório da ureia (H. pylori)", "Posso beber água antes do teste respiratório?",
     "Em geral só água sem gás é liberada, e apenas até o tempo indicado no seu preparo. Fora isso, o jejum vale para comida e outras bebidas. Se tiver dúvida, avise a equipe da clínica.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Posso fazer exercício físico antes do teste da ureia?",
     "O ideal é não se exercitar antes do exame. O teste é feito com você em repouso, sentado, então chegue tranquilo e sem esforço.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Bebida alcoólica atrapalha o teste respiratório?",
     "Sim, o preparo pede para evitar bebidas alcoólicas e bebidas com gás por um período antes do exame. Esse período está descrito na sua orientação. Seguir isso ajuda o resultado a sair confiável.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "O teste respiratório da ureia dói ou precisa de sedação?",
     "Não dói e não precisa de sedação. Você apenas sopra em um recipiente de coleta e toma o líquido do teste. É um exame simples e não invasivo.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "O teste respiratório da ureia usa radiação?",
     "Não. A ureia usada no teste é marcada com uma substância não radioativa. Por isso o exame é considerado seguro.",
     ("CEFIDI - Teste respiratório do H. pylori", "https://cefidi.com.br/exames/teste-respiratorio-do-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Grávida pode fazer o teste respiratório da ureia?",
     "Segundo as fontes, o teste não é radioativo e pode ser feito em gestantes e também em crianças. Mesmo assim, avise a equipe da clínica que você está grávida ou pode estar. Assim eles seguem o protocolo do local.",
     ("CEFIDI - Teste respiratório do H. pylori", "https://cefidi.com.br/exames/teste-respiratorio-do-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Criança pode fazer o teste respiratório da ureia?",
     "Sim, o exame não é radioativo e pode ser feito em crianças. A preparação costuma ser adaptada à idade, então siga o preparo que vier no agendamento.",
     ("CEFIDI - Teste respiratório do H. pylori", "https://cefidi.com.br/exames/teste-respiratorio-do-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Quanto tempo leva o teste respiratório da ureia no total?",
     "É um exame rápido, que em geral termina em menos de uma hora. Grande parte desse tempo é uma espera sentado entre as duas coletas de ar.",
     ("Laboratório Vital - Exame de urease respiratória", "https://labvital.com.br/glossario/exame-de-urease-respiratoria-para-h-pylori-como-funciona/")),
    ("Teste respiratório da ureia (H. pylori)", "Preciso ficar internado para fazer o teste respiratório?",
     "Não. O exame é feito na própria clínica ou laboratório, sem internação, e você volta para casa em seguida.",
     ("CEFIDI - Teste respiratório do H. pylori", "https://cefidi.com.br/exames/teste-respiratorio-do-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Devo anotar os remédios que usei antes do teste da ureia?",
     "Sim, vale levar uma lista dos remédios usados no período que antecede o exame, principalmente antibióticos e protetores do estômago. A equipe usa essa lista para orientar o preparo. Não pare seus remédios de rotina por conta própria.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Como sai o resultado do teste respiratório da ureia?",
     "O resultado costuma vir como positivo ou negativo, indicando se a bactéria foi detectada ou não. Quem pediu o exame vai interpretar junto com o seu histórico. Alguns remédios usados antes podem alterar o resultado.",
     ("Laboratório Vital - Exame de urease respiratória", "https://labvital.com.br/glossario/exame-de-urease-respiratoria-para-h-pylori-como-funciona/")),
    ("Teste respiratório da ureia (H. pylori)", "Já operei o estômago. Isso atrapalha o teste respiratório?",
     "Cirurgias no estômago e algumas doenças pulmonares podem interferir no resultado. Avise a equipe da clínica no agendamento para que ela oriente o melhor caminho.",
     ("Protocolo SUS-BH - Teste respiratório com ureia marcada", "https://fluxosusbh.pbh.gov.br/anexos/d33872ac2529cb701555933a9f558d92a95132ca.pdf")),
    ("Teste respiratório da ureia (H. pylori)", "A boca pode interferir no resultado do teste da ureia?",
     "Sim, bactérias da boca que produzem a mesma enzima podem interferir no teste. Por isso, siga as orientações de higiene bucal e de alimentação que vierem no seu preparo.",
     ("Protocolo SUS-BH - Teste respiratório com ureia marcada", "https://fluxosusbh.pbh.gov.br/anexos/d33872ac2529cb701555933a9f558d92a95132ca.pdf")),
    ("Teste respiratório da ureia (H. pylori)", "Depois do teste respiratório da ureia posso voltar à minha rotina?",
     "Como não há sedação nem contraste, em geral você pode retomar suas atividades e comer logo depois, se não houver outra orientação da clínica.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),
    ("Teste respiratório da ureia (H. pylori)", "Posso tomar meus outros remédios de rotina no dia do teste da ureia?",
     "Em geral remédios que não estão na lista de suspensão do seu preparo podem ser mantidos. Não interrompa nada por conta própria. Se ficar em dúvida sobre algum, avise a equipe da clínica antes do exame.",
     ("Felipe Gastro - Teste respiratório para H. pylori", "https://felipegastro.com.br/teste-respiratorio-para-h-pylori/")),

    # ---------------- Colonografia por tomografia ----------------
    ("Colonografia por tomografia (colonoscopia virtual)", "A colonoscopia virtual dói?",
     "Não costuma doer, porque a sonda usada não percorre o intestino. Pode haver um leve desconforto pelo gás colocado para abrir o intestino, que passa pouco depois do exame.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Preciso de sedação ou anestesia na colonoscopia virtual?",
     "Não. O exame é feito com você acordado, sem sedação e sem anestesia. Por isso costuma ser bem tolerado.",
     ("Dasa - Colonoscopia virtual", "https://nav.dasa.com.br/blog/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Como o gás é colocado no intestino durante a colonoscopia virtual?",
     "Uma sonda fina e flexível é posicionada no reto para liberar gás e dilatar o intestino. Isso deixa todas as partes visíveis nas imagens. É normal sentir a barriga cheia por um momento.",
     ("Hospital São Luiz - Colonoscopia virtual", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/tomografia-computadorizada/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Quanto tempo dura a colonoscopia virtual?",
     "A parte na sala de tomografia costuma ser rápida, de poucos minutos. Reserve um tempo extra para a recepção e para descansar um pouco depois, se sentir a barriga desconfortável.",
     ("Dasa - Colonoscopia virtual", "https://nav.dasa.com.br/blog/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Posso dirigir depois da colonoscopia virtual?",
     "Algumas unidades pedem que o paciente venha com um acompanhante adulto e não dirija depois. Outras liberam a rotina normal. Siga o que estiver escrito no seu preparo e pergunte à recepção se ficar em dúvida.",
     ("Hospital São Luiz - Colonoscopia virtual", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/tomografia-computadorizada/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Preciso de acompanhante na colonoscopia virtual?",
     "Em algumas unidades sim, e o acompanhante precisa ser maior de idade e levar documento. Não leve crianças, pois normalmente não há como cuidar delas durante o exame. Veja a regra no seu agendamento.",
     ("Hospital São Luiz - Colonoscopia virtual", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/tomografia-computadorizada/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Grávida pode fazer colonoscopia virtual?",
     "Em geral não, porque o exame usa radiação. Se houver qualquer chance de gravidez, avise a equipe da clínica antes de marcar ou de começar o preparo.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Tenho alergia a contraste. Posso fazer a colonoscopia virtual?",
     "Avise a equipe da clínica sobre alergias, principalmente a contraste iodado, e também a látex ou a algum alimento. Assim eles decidem como seguir com segurança. Não tome o contraste do preparo sem essa conversa.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Posso tomar meus remédios de rotina durante o preparo da colonoscopia virtual?",
     "Em geral os remédios de rotina podem ser mantidos, de preferência com um pouco de água. Os laxantes do preparo esvaziam o intestino e podem levar embora parte do que você toma, então siga o que estiver no seu material.",
     ("Felippe Mattoso - Colonoscopia virtual", "https://www.fmattoso.com.br/para-voce/exames/colonoscopia-virtual-por-tomografia-computadorizada")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Sou diabético ou uso anticoagulante. Preciso avisar algo na colonoscopia virtual?",
     "Sim. Avise a equipe da clínica se você usa remédio para diabetes, como a metformina, ou anticoagulante. Eles dizem como fazer o preparo com esses remédios.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Posso usar joias e maquiagem na colonoscopia virtual?",
     "O melhor é ir sem joias, brincos, pingentes, relógio, esmalte, maquiagem e gel no cabelo. Objetos assim podem aparecer nas imagens e atrapalhar.",
     ("Felippe Mattoso - Colonoscopia virtual", "https://www.fmattoso.com.br/para-voce/exames/colonoscopia-virtual-por-tomografia-computadorizada")),
    ("Colonografia por tomografia (colonoscopia virtual)", "E se eu me atrasar no dia da colonoscopia virtual?",
     "Chegue com antecedência, porque há triagem antes do exame. Atrasos podem obrigar a remarcar, e isso significa repetir todo o preparo.",
     ("Ecomax - Preparo para colonoscopia por tomografia", "https://ecomax-cdi.com.br/Preparos/Colonoscopia_por_TC/Colonoscopia_por_TC-COLONOSCOPIA_POR_TOMOGRAFIA.pdf")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Vomitei durante o preparo da colonoscopia virtual. O que faço?",
     "Entre em contato com a clínica logo, pelo telefone do seu material. A equipe orienta o que fazer, para você não perder o preparo nem exagerar nos remédios.",
     ("Ecomax - Preparo para colonoscopia por tomografia", "https://ecomax-cdi.com.br/Preparos/Colonoscopia_por_TC/Colonoscopia_por_TC-COLONOSCOPIA_POR_TOMOGRAFIA.pdf")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Posso beber água no dia da colonoscopia virtual?",
     "No dia do exame o preparo costuma liberar apenas água e os remédios com um golinho de água. Comida e outras bebidas ficam de fora depois do horário indicado no seu material.",
     ("Ecomax - Preparo para colonoscopia por tomografia", "https://ecomax-cdi.com.br/Preparos/Colonoscopia_por_TC/Colonoscopia_por_TC-COLONOSCOPIA_POR_TOMOGRAFIA.pdf")),
    ("Colonografia por tomografia (colonoscopia virtual)", "O que costuma poder comer na dieta antes da colonoscopia virtual?",
     "A dieta evita fibras, sementes, gordura e carne vermelha. Costuma liberar caldos coados, sucos coados, chás, gelatinas, água de coco e alguns alimentos leves. A lista exata está no seu preparo.",
     ("Ecomax - Preparo (Picoprep) para colonoscopia por tomografia", "https://ecomax-cdi.com.br/Preparos/Colonoscopia_por_TC/Colonoscopia_por_TC-COLONOSCOPIA_POR_TOMOGRAFIA.pdf")),
    ("Colonografia por tomografia (colonoscopia virtual)", "É normal ir muitas vezes ao banheiro durante o preparo?",
     "Sim, os laxantes servem para limpar o intestino. Fique perto de um banheiro, beba os líquidos permitidos e caminhe um pouco. Isso ajuda a eliminar gases e resíduos.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Em quais situações a colonoscopia virtual pode não ser feita?",
     "Algumas condições impedem o exame, como obstrução do intestino, inflamação aguda em certas partes do intestino, gravidez, claustrofobia intensa ou limites de peso do aparelho. Avise a equipe da clínica sobre qualquer uma delas ao agendar.",
     ("Felippe Mattoso - Colonoscopia virtual", "https://www.fmattoso.com.br/para-voce/exames/colonoscopia-virtual-por-tomografia-computadorizada")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Quando sai o resultado da colonoscopia virtual?",
     "O prazo varia conforme a unidade e está informado no comprovante do agendamento. Em geral o laudo fica pronto em poucos dias úteis, e quem pediu o exame vai explicar o que ele mostra.",
     ("Hospital São Luiz - Colonoscopia virtual", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/tomografia-computadorizada/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "A colonoscopia virtual retira alguma coisa do intestino?",
     "Não. Ela só gera imagens, sem cortes e sem coleta de material. Se algo precisar de outro tipo de avaliação, quem pediu o exame decide o próximo passo.",
     ("Dasa - Colonoscopia virtual", "https://nav.dasa.com.br/blog/colonoscopia-virtual")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Depois da colonoscopia virtual posso voltar às minhas atividades?",
     "Na maioria dos casos sim, sem restrição prolongada de alimentação. Se a barriga estiver desconfortável, espere melhorar antes de sair da unidade. Beba líquidos para ajudar a eliminar o contraste.",
     ("Tua Saúde - Colonoscopia virtual", "https://www.tuasaude.com/colonoscopia-virtual/")),
    ("Colonografia por tomografia (colonoscopia virtual)", "Menor de idade pode fazer colonoscopia virtual?",
     "Algumas unidades não realizam o exame em menores de idade. Se for o caso de um adolescente, avise a equipe da clínica ao agendar para saber se é possível.",
     ("Felippe Mattoso - Colonoscopia virtual", "https://www.fmattoso.com.br/para-voce/exames/colonoscopia-virtual-por-tomografia-computadorizada")),

    # ---------------- Ultrassonografia de abdome total ----------------
    ("Ultrassonografia de abdome total", "O ultrassom de abdome total dói?",
     "Não, o exame é indolor. Você pode sentir só uma leve pressão do aparelho na barriga, principalmente se a região estiver sensível.",
     ("Hospital de Clínicas de Itajubá - Ultrassom de abdome total", "https://hcitajuba.org.br/blog/ultrassom-de-abdome-total-o-que-voce-precisa-saber/")),
    ("Ultrassonografia de abdome total", "Para que serve o gel no ultrassom de abdome total?",
     "O gel elimina o ar entre a pele e o aparelho, o que melhora a imagem. Ele pode estar um pouco frio, mas não machuca a pele e é limpo com papel ao final.",
     ("AmorSaúde - Ultrassom abdominal", "https://blog.amorsaude.com.br/ultrassom-abdominal/")),
    ("Ultrassonografia de abdome total", "Quanto tempo demora o ultrassom de abdome total?",
     "Em geral é um exame rápido, e o tempo varia conforme a complexidade do que precisa ser avaliado. Chegue com folga para a recepção e para o preparo da sala.",
     ("AmorSaúde - Ultrassom abdominal", "https://blog.amorsaude.com.br/ultrassom-abdominal/")),
    ("Ultrassonografia de abdome total", "Que roupa devo usar no ultrassom de abdome total?",
     "Use roupas confortáveis e soltas, de preferência de duas peças, para deixar a barriga à mostra com facilidade. Em alguns locais pode ser oferecido um avental.",
     ("Hospital de Clínicas de Itajubá - Ultrassom de abdome total", "https://hcitajuba.org.br/blog/ultrassom-de-abdome-total-o-que-voce-precisa-saber/")),
    ("Ultrassonografia de abdome total", "Posso tomar meus remédios de rotina antes do ultrassom de abdome total?",
     "Na maioria dos casos sim, com um pouco de água. Não suspenda nada por conta própria e avise a equipe da clínica sobre todos os remédios que usa.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome total", "Uso insulina. Como fica o jejum do ultrassom de abdome total?",
     "Avise a equipe da clínica que você usa insulina ou outro remédio para diabetes, para que o horário do exame e do preparo seja combinado. Não ajuste a dose sozinho.",
     ("Hospital de Clínicas de Itajubá - Mitos e verdades sobre ultrassom de abdome total", "https://hcitajuba.org.br/blog/mitos-verdades-sobre-ultrassom-abdome-total/")),
    ("Ultrassonografia de abdome total", "Posso tomar café antes do ultrassom de abdome total?",
     "O café costuma ser incluído entre as bebidas a evitar durante o jejum, porque pode estimular a vesícula e o intestino. Siga o que estiver no seu preparo.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome total", "O que acontece se eu comer antes do ultrassom de abdome total?",
     "Os gases e o alimento no estômago e no intestino podem esconder órgãos e limitar o exame. Pode ser necessário repetir ou remarcar. Se comeu sem querer, avise a equipe assim que chegar.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome total", "Grávida ou criança pode fazer ultrassom de abdome total?",
     "Sim, o exame é seguro para adultos, crianças e gestantes, pois não usa radiação. Nas crianças o jejum costuma ser menor, então siga a orientação que vier no agendamento.",
     ("Hospital de Clínicas de Itajubá - Mitos e verdades sobre ultrassom de abdome total", "https://hcitajuba.org.br/blog/mitos-verdades-sobre-ultrassom-abdome-total/")),
    ("Ultrassonografia de abdome total", "Posso dirigir e trabalhar depois do ultrassom de abdome total?",
     "Sim. Não há sedação nem contraste, então você pode retomar a rotina logo depois do exame.",
     ("Hospital de Clínicas de Itajubá - Mitos e verdades sobre ultrassom de abdome total", "https://hcitajuba.org.br/blog/mitos-verdades-sobre-ultrassom-abdome-total/")),
    ("Ultrassonografia de abdome total", "Preciso tomar remédio para gases antes do ultrassom de abdome total?",
     "Só se a clínica pedir. Em alguns preparos há um remédio para reduzir gases, e as instruções dizem como e quando usar. Não tome por conta própria.",
     ("Clínica CEU - Como se preparar para um ultrassom abdominal", "https://www.clinicaceu.com.br/blog/como-se-preparar-para-um-ultrassom-abdominal/")),
    ("Ultrassonografia de abdome total", "Posso beber álcool ou fumar na véspera do ultrassom de abdome total?",
     "O preparo costuma pedir para evitar bebida alcoólica, frituras e cigarro na véspera. Um jantar leve ajuda a reduzir gases.",
     ("Clínica CEU - Como se preparar para um ultrassom abdominal", "https://www.clinicaceu.com.br/blog/como-se-preparar-para-um-ultrassom-abdominal/")),
    ("Ultrassonografia de abdome total", "Por que os gases atrapalham o ultrassom de abdome total?",
     "O ar do intestino reflete as ondas do aparelho e cria sombras que escondem órgãos como o pâncreas. Por isso o preparo tenta reduzir gases antes do exame.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome total", "Quais órgãos o ultrassom de abdome total mostra?",
     "Ele avalia fígado, vesícula, vias biliares, pâncreas, baço, rins, bexiga e grandes vasos, além de parte das alças do intestino. O detalhe depende do que foi pedido.",
     ("Instituto da Imagem - Ultrassonografia abdominal total", "https://www.instituto.med.br/ultrassonografia-abdominal-total-perguntas-e-respostas/")),
    ("Ultrassonografia de abdome total", "Meu filho vai fazer ultrassom de abdome. O jejum é igual ao do adulto?",
     "Nas crianças o jejum costuma ser menor e varia com a idade. Siga a orientação do preparo que recebeu e, para bebês, avise a equipe sobre os horários de mamada.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome total", "Tenho ultrassons antigos. Devo levar ao exame?",
     "Sim, leve exames anteriores de imagem se tiver. Eles ajudam a comparar o que mudou.",
     ("Centro Médico Berrini - Ultrassonografia de abdome superior", "https://centromedicoberrini.com.br/preparo-de-exames/ultrassonografia-abdomen-superior-figado-vias-biliares-vesicula-pancreas-e-baco")),
    ("Ultrassonografia de abdome total", "Como será entregue o resultado do ultrassom de abdome total?",
     "O laudo descreve os órgãos, seus tamanhos e o que foi visto. Ele deve ser levado a quem pediu o exame, que explica o significado para o seu caso.",
     ("AmorSaúde - Ultrassom abdominal", "https://blog.amorsaude.com.br/ultrassom-abdominal/")),

    # ---------------- Ultrassonografia de abdome superior ----------------
    ("Ultrassonografia de abdome superior", "Posso beber água no jejum do ultrassom de abdome superior?",
     "Em geral a água é liberada, mas só até um certo tempo antes do exame, conforme o seu preparo. Beber além disso pode atrapalhar a imagem.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "O jejum do ultrassom de abdome superior é o mesmo para crianças?",
     "Não. Crianças costumam ter um jejum menor que o dos adultos, e ele muda conforme a idade. O tempo exato vem no preparo que você recebeu.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Meu bebê mamando pode fazer o ultrassom de abdome superior?",
     "Pode, e o preparo dos bebês costuma ser bem mais curto, com uma pausa depois da última mamada. Siga o tempo que estiver na sua orientação.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Sou diabética. O jejum do ultrassom de abdome superior muda?",
     "Para pessoas com diabetes o jejum costuma ser menor, para evitar queda de açúcar. Avise a equipe da clínica e siga o tempo indicado no seu preparo.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Posso chupar bala ou mascar chiclete no jejum do ultrassom de abdome superior?",
     "Não. Balas e chicletes contam como quebra do jejum, porque fazem você engolir ar e estimulam o estômago. Evite até o fim do exame.",
     ("Centro de Diagnóstico Conceber - Modo de preparo", "https://www.concebermanaus.com.br/exames-de-imagens/ultrassonografia-de-abdome-superior-(f%C3%ADgado,-vias-biliares,-ves%C3%ADcula,-p%C3%A2ncreas-e-ba%C3%A7o)")),
    ("Ultrassonografia de abdome superior", "O que o ultrassom de abdome superior avalia?",
     "Ele mostra fígado, vesícula, vias biliares, pâncreas e baço, e em alguns casos rins e outras estruturas da parte de cima da barriga. A lista final depende do pedido.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "O ultrassom de abdome superior dói e quanto demora?",
     "É indolor e não invasivo. A duração é curta e varia conforme a complexidade do que precisa ser visto.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Preciso tirar brincos, curativos ou talas no ultrassom de abdome superior?",
     "Só adornos, curativos ou talas removíveis que estejam na região a ser examinada. Se algo não puder ser retirado, avise a equipe antes do exame.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Grávida pode fazer o ultrassom de abdome superior?",
     "Sim, não há contraindicação para gestantes, pois o exame não usa radiação. Avise a equipe da clínica sobre a gravidez para que ela ajuste o atendimento.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Adolescente precisa de acompanhante no ultrassom de abdome superior?",
     "Menores de idade precisam estar com um responsável adulto até o fim do exame. Leve um documento de identidade dele.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Que alimentos devo evitar antes do ultrassom de abdome superior?",
     "Evite os que dão gases, como feijão, repolho, brócolis e refrigerante, e também frituras. Isso deixa as imagens mais nítidas.",
     ("Hospital São Luiz - Ultrassonografia de abdome superior", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/ultrassonografia/ultrassonografia-abdome-superior-figado-vias-biliares-vesicula-pancreas-baco")),
    ("Ultrassonografia de abdome superior", "Preciso de bexiga cheia no ultrassom de abdome superior?",
     "Em geral não é necessário, porque o foco é a parte de cima da barriga. Alguns pedidos combinam o exame com a pelve, e aí a bexiga cheia pode ser pedida. Siga o seu preparo.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome superior", "Café atrapalha o ultrassom de abdome superior?",
     "O café costuma ser evitado durante o jejum, porque pode estimular a vesícula e o intestino. Deixe para tomar depois do exame.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome superior", "Comi sem querer antes do ultrassom de abdome superior. E agora?",
     "Avise a equipe assim que chegar. A vesícula pode estar contraída e o estômago cheio, o que limita a imagem. Pode ser preciso remarcar.",
     ("Rafáh Rede Hospitalar - Preparo para ultrassom", "https://rafahredehospitalar.com/ultrasonografia/preparo-para-ultrassom/")),
    ("Ultrassonografia de abdome superior", "Devo levar exames antigos ao ultrassom de abdome superior?",
     "Sim, ultrassons anteriores ajudam a comparar. Leve também o pedido do exame.",
     ("Centro Médico Berrini - Ultrassonografia de abdome superior", "https://centromedicoberrini.com.br/preparo-de-exames/ultrassonografia-abdomen-superior-figado-vias-biliares-vesicula-pancreas-e-baco")),
    ("Ultrassonografia de abdome superior", "Posso fumar antes do ultrassom de abdome superior?",
     "O preparo costuma pedir para não fumar na véspera e no dia do exame. O cigarro pode aumentar gases e estimular o estômago.",
     ("Clínica CEU - Como se preparar para um ultrassom abdominal", "https://www.clinicaceu.com.br/blog/como-se-preparar-para-um-ultrassom-abdominal/")),
