# -*- coding: utf-8 -*-
"""Itens adicionais de FAQ (grupo 7): exames endoscopicos digestivos."""

_MDE = ("Hospital Mãe de Deus - Colonoscopia: indicações, preparo e dúvidas", "https://www.maededeus.com.br/Blog/Artigo/colonoscopia-quando-fazer-como-e-o-preparo-e-principais-duvidas")
_DASA = ("Nav Dasa - Preparo para colonoscopia", "https://nav.dasa.com.br/blog/preparo-para-colonoscopia")
_UFU = ("HC-UFU (Ebserh) - Preparo e orientações para colonoscopia", "https://www.gov.br/ebserh/pt-br/hospitais-universitarios/regiao-sudeste/hc-ufu/saude/preparo-de-exames/c/colonoscopia-periodo-da-manha")
_MDS = ("MD.Saúde - Colonoscopia", "https://www.mdsaude.com/gastroenterologia/colonoscopia/")
_DER = ("Preparo para o exame de colonoscopia", "https://www.drderival.com/preparo-para-o-exame-de-colonoscopia.html")
_HDE = ("Hospital de Endoscopia - Dúvidas e perguntas", "https://hospitaldeendoscopia.com.br/duvidas-e-perguntas/")
_USG = ("Unimed Serra Gaúcha - 5 perguntas e respostas sobre endoscopia", "https://www.unimedserragaucha.com.br/blog/5-perguntas-e-respostas-sobre-endoscopia")
_HP = ("Hospital Português - Endoscopia digestiva alta", "https://www.hportugues.com.br/medicina-diagnostica/orientacoes/endoscopia-digestiva-alta/")
_UFO = ("Unimed Fortaleza - Tudo sobre endoscopia digestiva alta", "https://www.unimedfortaleza.com.br/blog/cuidar-de-voce/tudo-sobre-endoscopia-digestiva-alta")
_ART = ("Artur Parada - O que fazer antes da endoscopia digestiva alta", "https://arturparada.com.br/blog/o-que-fazer-antes-de-realizar-o-exame-de-endoscopia-digestiva-alta")
_IGED = ("IGED - Preparo para endoscopia e dúvidas comuns", "https://iged.com.br/exames/preparo-para-endoscopia-quanto-tempo-de-jejum-cuidados-pre-exame-e-duvidas-mais-comuns/")
_BPE = ("Beneficência Portuguesa - Endoscopia: preparo", "https://www.bp.org.br/diagnosticos/endoscopia/preparo")
_BPR = ("Beneficência Portuguesa - Orientações para retossigmoidoscopia flexível", "https://www.bp.org.br/diagnosticos/retossigmoidoscopia-flexivel/preparo")
_HPR = ("Hospital Português - Retossigmoidoscopia", "https://www.hportugues.com.br/servicos/medicina-diagnostica/orientacoes/retossigmoidoscopia/")
_ABCR = ("Hospital ABC - Retossigmoidoscopia", "https://www.abc.med.br/exames-e-procedimentos/retossigmoidoscopia-como-e-o-procedimento")
_GCL = ("Gastroclass - Orientações retossigmoidoscopia flexível", "https://gastroclass.com.br/orientacoes-retossigmoidoscopia-flexivel/")
_GCN = ("Gastroclinic - Preparo para retossigmoidoscopia flexível", "https://gastroclinic.com.br/wp-content/uploads/2023/12/Preparo_para_Retossigmoidoscopia_flexivel.pdf")
_SOB = ("SOBED - Videoenteroscopia assistida por balão", "https://www.sobed.org.br/geral/orientacao-ao-paciente/exames/videoenteroscopia-assistida-por-balao/")
_ABE = ("Hospital ABC - Enteroscopia por balão", "https://www.abc.med.br/exames-e-procedimentos/enteroscopia-por-balao")
_EMF = ("Em Foco - Enteroscopia: quando investigar o intestino delgado", "https://emfoco.med.br/enteroscopia-quando-investigar-o-intestino-delgado/")
_SGB = ("Sociedade de Gastroenterologia da Bahia - Endoscopia", "https://sgb-ba.com.br/endoscopia/")
_ALTA = ("Alta Diagnósticos - Cápsula endoscópica", "https://altadiagnosticos.com.br/saude/capsula-endoscopica/")
_MAL = ("Dr. Everson Malluta - Dúvidas sobre cápsula endoscópica", "https://dreversonmalluta.com.br/duvidas-sobre-capsula-endoscopica/")
_ECL = ("Endoclin - Cápsula endoscópica", "https://www.endoclin.com.br/site/exames-e-procedimentos/capsula-endoscopica/")
_ENC = ("Endostar - Orientações para cápsula endoscópica", "https://endostar.com.br/wp-content/uploads/2023/11/CAPSULA-ENDOSCOPICA_.pdf")
_WES = ("Wescope - Cápsula endoscópica", "https://wescope.com.br/capsula-endoscopica/")
_RDA = ("Rede D'Or - Ecoendoscopia alta", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/endoscopia/ecoendoscopia-alta")
_RDP = ("Rede D'Or - Ecoendoscopia alta com punção por agulha", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/endoscopia/ecoendoscopia-alta-com-puncao-por-agulha")
_DAE = ("Nav Dasa - Ecoendoscopia", "https://nav.dasa.com.br/blog/ecoendoscopia")
_ENE = ("Endostar - Preparo para ecoendoscopia alta", "https://endostar.com.br/wp-content/uploads/2023/09/Preparo-para-Ecoendoscopia-alta-para-impressao-Endostar.pdf")
_GLF = ("Gastrolife - Como é o exame de ecoendoscopia", "https://gastrolife.net/como-e-o-exame-de-ecoendoscopia/")

ITENS = [
    # ---------------- Colonoscopia ----------------
    ("Colonoscopia", "O que posso comer na véspera do exame?",
     "Em geral a alimentação fica leve e sem fibras, com coisas como pão branco, arroz branco, massa sem molho vermelho, frango ou peixe cozidos e gelatina clara. Depois de certo horário só entram líquidos claros. Siga o cardápio e os horários que vieram no seu preparo.", _DER),
    ("Colonoscopia", "Quais alimentos devo evitar no preparo?",
     "Evite tudo que tem fibra ou resíduo, como feijão, grãos integrais, verduras, legumes, frutas com casca ou sementes, e também leite. Alimentos avermelhados também atrapalham a limpeza. Quanto menos resíduo, melhor a imagem do intestino.", _UFU),
    ("Colonoscopia", "Quais líquidos são considerados claros?",
     "Água, água de coco, chás claros, caldos coados, refrigerantes claros, sucos coados de cor clara e gelatina de cor clara costumam ser aceitos. A regra é poder enxergar através do líquido. Siga a lista do seu preparo.", _UFU),
    ("Colonoscopia", "Posso tomar líquidos com corante vermelho, roxo ou azul?",
     "Não. Corantes dessas cores podem parecer sangue dentro do intestino e atrapalhar a avaliação durante o exame. Escolha líquidos transparentes ou de cor bem clara.", _DER),
    ("Colonoscopia", "Por que preciso beber tanto líquido claro durante o preparo?",
     "O líquido ajuda o laxante a funcionar e evita que você fique desidratado enquanto o intestino é esvaziado. Beba de forma constante ao longo do dia, no volume indicado no seu preparo.", _DASA),
    ("Colonoscopia", "Estou com enjoo ao tomar a solução laxante, o que faço?",
     "Faça uma pausa curta e depois retome bem devagar, em goles pequenos. Se o enjoo continuar ou você vomitar, avise a equipe da clínica para saber como seguir. Não abandone o preparo por conta própria.", _DER),
    ("Colonoscopia", "Por que existe um jejum completo mesmo depois de tomar o laxante?",
     "Esse período sem nada, nem água, é uma medida de segurança para a sedação. Um estômago vazio reduz o risco de o conteúdo voltar durante o procedimento. Respeite o tempo indicado no seu preparo.", _DER),
    ("Colonoscopia", "Tomo ferro ou vitaminas com ferro, preciso parar antes do exame?",
     "Suplementos de ferro costumam entrar na lista de itens que precisam de suspensão antes do exame, pelo tempo indicado no seu preparo. Avise a equipe da clínica se você usa esse tipo de produto e não interrompa nada sem orientação.", _MDE),
    ("Colonoscopia", "Estou grávida ou menstruada, posso fazer a colonoscopia?",
     "Gestantes, mulheres menstruadas, idosos e pessoas com condições especiais podem precisar de um protocolo adaptado. Avise a equipe da clínica no agendamento para que o seu caso seja avaliado com cuidado.", _MDE),
    ("Colonoscopia", "Que roupa devo usar no dia da colonoscopia?",
     "Prefira roupas confortáveis e de algodão, sem peças de metal. Deixe joias e piercings em casa e mantenha as unhas naturais, sem esmalte, porque isso atrapalha o monitoramento durante a sedação.", _DER),
    ("Colonoscopia", "O que devo levar no dia do exame?",
     "Leve documento de identidade, carteirinha do convênio, a autorização do procedimento, o pedido médico e o seu acompanhante. Se tiver exames anteriores, leve também.", _USG),
    ("Colonoscopia", "Minha pele fica irritada de tanto ir ao banheiro, o que posso fazer?",
     "É comum a região ficar sensível durante o preparo. Lenços umedecidos sem perfume, do tipo usado em bebês, ajudam a higienizar com mais suavidade do que o papel comum.", _DER),
    ("Colonoscopia", "Posso me preparar se tenho intestino preso ou dificuldade de locomoção?",
     "Nesses casos existe um preparo reforçado, com passos extras para garantir a limpeza. Avise a equipe da clínica no agendamento sobre prisão de ventre, mobilidade reduzida ou remédios que afetam o intestino.", _DER),
    ("Colonoscopia", "O exame pode ser cancelado se o preparo não ficou bom?",
     "Sim. Se o intestino não estiver limpo o bastante, a imagem fica prejudicada e o exame pode ser cancelado ou remarcado. Por isso, siga o preparo à risca e avise a equipe se algo não saiu como o esperado.", _USG),
    ("Colonoscopia", "Um preparo malfeito faz diferença mesmo?",
     "Faz muita diferença. Restos de fezes podem esconder alterações pequenas e impedir a visão completa do intestino. Um bom preparo é a parte do exame que fica nas suas mãos.", _DER),
    ("Colonoscopia", "Vou me lembrar do exame depois da sedação?",
     "Normalmente não. A sedação faz a pessoa ficar sonolenta em poucos instantes e a maioria não guarda lembrança do procedimento. A recuperação completa costuma se dar até o dia seguinte.", _MDS),
    ("Colonoscopia", "Por que sinto gases e cólica depois da colonoscopia?",
     "Durante o exame entra ar no intestino para abrir as paredes e permitir a visão. Depois, é normal sentir vontade de soltar gases e uma leve cólica. Caminhar um pouco ajuda a eliminar o ar.", _MDS),
    ("Colonoscopia", "Quando posso voltar a comer normalmente depois do exame?",
     "Em geral a alimentação é liberada quando você está bem acordado, começando por algo leve. Se houve alguma retirada de material, a equipe pode dar orientações específicas.", _MDS),
    ("Colonoscopia", "Posso fazer exercício físico depois da colonoscopia?",
     "Atividades do dia a dia costumam ser liberadas no dia seguinte. Se foram retirados pólipos ou feitas biópsias, esforços intensos como corrida e musculação podem precisar de um período de pausa indicado pela equipe.", _MDS),
    ("Colonoscopia", "É normal sair um pouco de sangue nas fezes depois do exame?",
     "Um pouco de sangue nas primeiras evacuações pode acontecer quando houve biópsia ou retirada de pólipos. Se o sangramento for intenso ou não parar, procure atendimento e avise a clínica.", _MDS),
    ("Colonoscopia", "Quais sinais depois da colonoscopia pedem atenção urgente?",
     "Dor forte na barriga, barriga muito inchada, vômitos, febre e sangramento intenso ou que não para. Procure atendimento e informe que fez colonoscopia.", _MDS),
    ("Colonoscopia", "O resultado da colonoscopia sai na hora?",
     "A equipe costuma conversar sobre o que foi visto logo após o exame. Se houve biópsia, o material vai para análise e o resultado é entregue mais tarde, no prazo que a clínica informar.", _USG),
    ("Colonoscopia", "Ficarei em observação depois do exame?",
     "Sim. Após a sedação você permanece em uma área de recuperação até estar bem desperto e estável. Só depois recebe alta acompanhado.", _MDS),
    ("Colonoscopia", "Durante a colonoscopia podem retirar pólipos ou fazer biópsia?",
     "Sim. Se algo precisar de análise ou remoção, isso pode ser feito na mesma sessão. O material retirado é enviado para estudo e o resultado sai depois.", _HDE),
    ("Colonoscopia", "Posso comer alimento sólido no dia do exame?",
     "Não. Depois do horário definido no preparo, só entram líquidos claros, e mais perto do exame nem isso. Siga a linha do tempo que veio na sua orientação.", _UFU),

    # ---------------- Endoscopia digestiva alta ----------------
    ("Endoscopia digestiva alta", "O que devo comer na véspera da endoscopia?",
     "Faça uma alimentação leve e evite frituras, carne vermelha, molhos gordurosos, pratos muito temperados e comidas de difícil digestão. Álcool também deve ficar de fora. Depois, respeite o jejum indicado no seu preparo.", _ART),
    ("Endoscopia digestiva alta", "Posso ir de unha pintada ou maquiada?",
     "Melhor não. Esmalte e maquiagem podem atrapalhar o aparelho que mede o oxigênio no sangue durante a sedação. Retire o esmalte antes de ir.", _ART),
    ("Endoscopia digestiva alta", "Vou engasgar ou ter dificuldade para respirar durante o exame?",
     "O aparelho é fino e a garganta é anestesiada, o que reduz a vontade de engasgar. Você respira normalmente durante todo o exame, pois o aparelho não bloqueia a passagem do ar.", _UFO),
    ("Endoscopia digestiva alta", "Vou dormir completamente durante a endoscopia?",
     "Você recebe anestesia local na garganta e sedação na veia. Fica relaxado e a maioria das pessoas dorme durante o exame, mas o grau de sedação depende de cada caso.", _UFO),
    ("Endoscopia digestiva alta", "Gestantes podem fazer endoscopia?",
     "Na gravidez o exame só é feito se a equipe avaliar que é realmente necessário. Avise que está grávida ou que suspeita estar já no agendamento.", _UFO),
    ("Endoscopia digestiva alta", "O que devo levar no dia da endoscopia?",
     "Leve documento com foto, carteirinha do convênio ou autorização, o pedido médico, exames anteriores e seu acompanhante. Leve também os remédios que precisar tomar depois do exame.", _HP),
    ("Endoscopia digestiva alta", "Posso tomar leite ou antiácido antes da endoscopia?",
     "Não. Leite e antiácidos deixam resíduos no estômago e atrapalham a imagem. Café com leite também deve ser evitado. Siga a lista de líquidos permitidos no seu preparo.", _HP),
    ("Endoscopia digestiva alta", "Quando retomo meus remédios depois da endoscopia?",
     "A equipe costuma orientar que os remédios de uso contínuo sejam retomados depois do exame, junto com a primeira refeição. Siga o que estiver no seu preparo e leve os medicamentos com você.", _HP),
    ("Endoscopia digestiva alta", "Posso beber álcool ou tomar decisões importantes depois do exame?",
     "Não no mesmo dia. A sedação deixa o raciocínio e os reflexos mais lentos. Evite bebida alcoólica, contratos e tarefas que exijam atenção até a sedação passar totalmente.", _IGED),
    ("Endoscopia digestiva alta", "Preciso trazer alguma carta ou exame se tenho problema no coração ou no rim?",
     "Alguns serviços pedem carta e exames complementares para pessoas com doença cardíaca ou renal, para quem tem marca-passo e para idosos. Avise a equipe da clínica e siga a lista do seu preparo.", _BPE),
    ("Endoscopia digestiva alta", "Tenho alergia a látex, isso importa?",
     "Sim. Avise no agendamento, para que a equipe use materiais adequados. O mesmo vale se você precisar de algum tipo de acessibilidade.", _BPE),
    ("Endoscopia digestiva alta", "Como é o preparo de crianças e bebês para a endoscopia?",
     "O jejum de bebês varia conforme eles tomem leite materno ou fórmula, e o de crianças maiores segue o que a clínica informar. Um responsável legal deve acompanhar a criança durante toda a permanência.", _BPE),
    ("Endoscopia digestiva alta", "Tenho acalasia, o preparo é diferente?",
     "Sim. Nesse caso costuma haver dieta líquida na véspera e um jejum mais longo. Avise a equipe sobre a condição e siga o seu preparo específico.", _BPE),
    ("Endoscopia digestiva alta", "Quanto tempo fico em observação depois da endoscopia?",
     "Depois do exame você descansa na sala de recuperação até a sedação passar e estar bem acordado. Só então recebe alta com o acompanhante e, em muitos serviços, um lanche leve.", _USG),
    ("Endoscopia digestiva alta", "O resultado da endoscopia sai na hora?",
     "O laudo costuma sair logo após o exame. Se foi feita biópsia, o resultado da análise demora mais e é entregue depois, no prazo informado pela clínica.", _USG),
    ("Endoscopia digestiva alta", "O médico pode fazer biópsia durante a endoscopia?",
     "Sim. Se for necessário, pequenos fragmentos podem ser colhidos na hora, inclusive para testar a presença de bactérias no estômago, e enviados para análise.", _HDE),
    ("Endoscopia digestiva alta", "Que roupa é indicada para a endoscopia?",
     "Roupa confortável e sapatos baixos. Evite salto alto e deixe joias em casa. Retire óculos e próteses dentárias antes do exame.", _IGED),
    ("Endoscopia digestiva alta", "A sedação da endoscopia é segura?",
     "Costuma ser aplicada por médico anestesista, com monitoramento contínuo dos sinais vitais. Por isso é importante avisar sobre todos os seus problemas de saúde e remédios.", _IGED),
    ("Endoscopia digestiva alta", "Posso fazer exercício depois da endoscopia?",
     "Melhor deixar para o dia seguinte. Depois do exame, o corpo ainda está sob efeito da sedação. Descanse e retome a atividade física apenas quando estiver bem desperto e sem tontura.", _HDE),
    ("Endoscopia digestiva alta", "O exame pode não ser feito se eu não seguir o preparo?",
     "Sim. Se houver comida ou líquido no estômago, o exame pode ser adiado ou cancelado por segurança. Por isso, siga exatamente o jejum indicado.", _ART),
    ("Endoscopia digestiva alta", "Idosos precisam de algum cuidado extra para a endoscopia?",
     "Alguns serviços pedem exames e uma carta com a avaliação da saúde de pessoas idosas antes do procedimento. Veja a lista do seu agendamento e avise a equipe sobre as doenças e os remédios que usa.", _BPE),

    # ---------------- Retossigmoidoscopia ----------------
    ("Retossigmoidoscopia", "O que comer na véspera da retossigmoidoscopia?",
     "A dieta costuma ser leve, sem gordura, sem carne vermelha e sem fibras. Evite bebida alcoólica. Siga as instruções do seu preparo quanto a horários e alimentos permitidos.", _BPR),
    ("Retossigmoidoscopia", "Uso caneta para diabetes ou emagrecimento, preciso avisar?",
     "Sim. Alguns desses remédios precisam ser suspensos antes do exame, por um período que varia conforme o medicamento e está no seu preparo. Avise a equipe da clínica qual você usa.", _BPR),
    ("Retossigmoidoscopia", "Posso ir com cílios postiços, apliques ou unhas de gel?",
     "Alguns serviços pedem que apliques de cabelo, cílios postiços e unhas postiças sejam retirados antes do exame. Verifique a orientação do seu agendamento.", _BPR),
    ("Retossigmoidoscopia", "Tenho marca-passo, posso fazer o exame?",
     "Pessoas com marca-passo costumam ser orientadas a levar uma carta de autorização do cardiologista. Avise a equipe da clínica no agendamento.", _BPR),
    ("Retossigmoidoscopia", "Como funciona a lavagem intestinal com enema?",
     "O conteúdo do frasco é aplicado pelo ânus, com a pessoa deitada. Depois, é preciso reter o líquido o quanto conseguir antes de ir ao banheiro. O número de frascos e os horários de aplicação estão no seu preparo.", _GCL),
    ("Retossigmoidoscopia", "Em que posição fico durante o exame?",
     "Você fica deitado de lado, com os joelhos dobrados, o que facilita a passagem do aparelho. A equipe explica cada etapa e ajuda no posicionamento.", _ABCR),
    ("Retossigmoidoscopia", "O que vou sentir durante o exame?",
     "É comum sentir pressão, cólica leve e vontade de evacuar, por causa do ar colocado para abrir o intestino. O desconforto costuma ser suportável e passa logo. Se precisar, sinalize à equipe.", _ABCR),
    ("Retossigmoidoscopia", "Preciso de sedação para a retossigmoidoscopia?",
     "Depende do serviço. Em alguns o exame é feito sem sedação, com gel anestésico, e em outros com sedação. Veja o que consta na sua orientação, pois isso muda regras como jejum e acompanhante.", _HPR),
    ("Retossigmoidoscopia", "O médico usa algum gel durante o exame?",
     "Sim, costuma ser aplicado um gel lubrificante com efeito anestésico para facilitar a entrada do aparelho e diminuir o desconforto.", _ABCR),
    ("Retossigmoidoscopia", "Posso voltar às atividades logo depois do exame?",
     "Quando não há sedação, a liberação costuma ser imediata. Se houve sedação, siga as regras de repouso e acompanhante que constam na sua orientação.", _ABCR),
    ("Retossigmoidoscopia", "É normal sair um pouco de sangue na primeira evacuação depois?",
     "Um pequeno sangramento na primeira evacuação pode acontecer e costuma ser passageiro. Se for volumoso ou persistir, procure atendimento.", _ABCR),
    ("Retossigmoidoscopia", "Por que fico com gases e a barriga inchada depois?",
     "Durante o exame entra ar no intestino para facilitar a visão. Depois, gases, inchaço e leve desconforto são comuns e passam em poucas horas.", _ABCR),
    ("Retossigmoidoscopia", "Preciso beber bastante líquido depois do exame?",
     "Sim, algumas orientações recomendam beber bastante líquido depois do preparo para evitar a desidratação. Siga o que estiver no seu preparo.", _GCL),
    ("Retossigmoidoscopia", "Existem riscos na retossigmoidoscopia?",
     "Complicações graves são muito raras, como sangramento ou lesão da parede do intestino. Por isso, a equipe orienta observar sinais depois do exame.", _HPR),
    ("Retossigmoidoscopia", "Quais sintomas depois do exame exigem atendimento?",
     "Dor persistente na barriga, barriga muito inchada, sangramento, febre ou inchaço no local da injeção, se houve sedação na veia. Procure atendimento e informe que fez o exame.", _HPR),
    ("Retossigmoidoscopia", "O que devo levar no dia da retossigmoidoscopia?",
     "Documento de identidade, carteirinha ou autorização do convênio e o pedido médico. Se tiver exame anterior, leve também.", _HPR),
    ("Retossigmoidoscopia", "Meu acompanhante pode ir de moto ou bicicleta?",
     "Não. Quando o exame tem sedação, o acompanhante deve ser um adulto responsável, capaz de levar você em segurança. Ele não deve estar de moto ou bicicleta.", _GCN),
    ("Retossigmoidoscopia", "Posso usar joias e esmalte no dia do exame?",
     "Não. Deixe joias, alianças e adornos em casa e evite esmalte de cor escura. Avise se usa prótese dentária.", _GCN),
    ("Retossigmoidoscopia", "Como fica o remédio de diabetes e o de pressão no dia do exame?",
     "Em alguns serviços, remédios para diabetes não são tomados no dia do exame, e os de pressão são tomados no horário indicado no preparo. Siga a sua orientação e avise a equipe sobre tudo o que usa.", _GCN),
    ("Retossigmoidoscopia", "Uso aspirina, preciso avisar?",
     "Sim. Alguns preparos pedem a suspensão do ácido acetilsalicílico pelo tempo indicado. Avise a equipe e não interrompa por conta própria.", _GCL),
    ("Retossigmoidoscopia", "Retossigmoidoscopia é o mesmo que colonoscopia?",
     "Não. É uma versão mais curta, que examina apenas o reto e a parte final do intestino grosso. Por isso o preparo costuma ser mais simples que o da colonoscopia.", _HPR),
    ("Retossigmoidoscopia", "Posso marcar compromissos para o dia do exame?",
     "Melhor não. Alguns serviços orientam reservar o dia todo, porque podem ocorrer atrasos ou você pode precisar descansar.", _GCN),
    ("Retossigmoidoscopia", "Como sai o resultado se houver biópsia?",
     "O material é enviado para análise e o resultado é entregue depois, no prazo informado pela clínica.", _HPR),
    ("Retossigmoidoscopia", "Devo levar exames anteriores?",
     "Sim, se tiver. Comparar com exames feitos antes ajuda a equipe na avaliação.", _GCN),

    # ---------------- Enteroscopia ----------------
    ("Enteroscopia", "O que a enteroscopia examina que outros exames não alcançam?",
     "Ela permite ver o intestino delgado, uma região longa e de difícil acesso, que a endoscopia alta e a colonoscopia não alcançam por inteiro. O aparelho é um tubo flexível com câmera, e alguns modelos usam balões para avançar.", _ABE),
    ("Enteroscopia", "O exame é feito pela boca ou pelo ânus? Como saber?",
     "Depende da parte do intestino que precisa ser vista. A via oral alcança os trechos iniciais e a via anal, os trechos finais. Sua equipe informa qual via será usada e o preparo correspondente.", _EMF),
    ("Enteroscopia", "A enteroscopia demora mais que a endoscopia comum?",
     "Sim. Por examinar um trecho longo do intestino, costuma ser bem mais demorada que uma endoscopia ou colonoscopia. Por isso é feita em ambiente hospitalar, com suporte de anestesia.", _ABE),
    ("Enteroscopia", "Vou lembrar do exame depois de acordar?",
     "Em geral não. Como a sedação é profunda ou a anestesia é geral, você fica dormindo durante todo o procedimento e acorda depois na sala de recuperação.", _SOB),
    ("Enteroscopia", "Quais efeitos comuns aparecem depois da enteroscopia?",
     "Dor de garganta, enjoo, vômito, gases, inchaço e cólicas são comuns e costumam melhorar sozinhos. Se piorarem ou forem muito fortes, avise a equipe.", _ABE),
    ("Enteroscopia", "Quais são os riscos da enteroscopia?",
     "Como em outros exames endoscópicos, pode haver sangramento, lesão da parede do intestino e reações à sedação. Existem também riscos específicos, como inflamação do pâncreas ou paralisia temporária do intestino, que são pouco frequentes.", _ABE),
    ("Enteroscopia", "O exame pode ficar incompleto?",
     "Pode. Em alguns casos o aparelho não consegue alcançar todo o trecho planejado, e a equipe pode sugerir outra via ou outro exame para complementar.", _SOB),
    ("Enteroscopia", "Posso voltar para casa de moto ou de carona de moto?",
     "Não. A sedação afeta o raciocínio e os reflexos durante o dia todo. Volte com um adulto responsável, de carro ou transporte seguro, e não dirija nem ande de moto.", _SOB),
    ("Enteroscopia", "Quanto tempo fico em repouso depois do exame?",
     "Você fica em uma área de recuperação até os efeitos da medicação passarem, sob observação da equipe. Só depois recebe alta com o acompanhante.", _SOB),
    ("Enteroscopia", "Qual a diferença entre enteroscopia e cápsula endoscópica?",
     "A cápsula é engolida e só registra imagens, sem sedação e sem possibilidade de tratamento. A enteroscopia usa um aparelho, sob sedação, e permite colher biópsias e tratar alterações na mesma sessão.", _EMF),
    ("Enteroscopia", "Uso anticoagulante ou anti-inflamatório, preciso avisar antes da enteroscopia?",
     "Sim. Avise a equipe da clínica sobre esses remédios e sobre tudo o que você toma. Qualquer suspensão só deve seguir o que estiver no seu preparo.", _EMF),
    ("Enteroscopia", "Na via anal preciso tomar laxante?",
     "Sim. Pela via anal o intestino precisa ser limpo, com preparo semelhante ao da colonoscopia, que inclui dieta específica e laxante. Siga o seu preparo com atenção para não comprometer o exame.", _SOB),
    ("Enteroscopia", "Recebo laudo com as imagens depois?",
     "As imagens vão para o computador e o médico analisa e escreve o laudo com os achados. Se houver biópsia, o resultado dela sai mais tarde.", _ABE),
    ("Enteroscopia", "Quais sintomas depois do exame exigem atendimento imediato?",
     "Sangramento intenso, dor forte e crescente na barriga, ou sinais de inflamação do pâncreas, como dor forte com vômitos. Procure atendimento e informe que fez enteroscopia.", _ABE),
    ("Enteroscopia", "O exame permite tratar alguma alteração na mesma sessão?",
     "Sim. Além de ver, a enteroscopia com balão permite fazer biópsias e alguns tratamentos, como retirar pólipos ou tratar pontos de sangramento.", _SGB),

    # ---------------- Cápsula endoscópica ----------------
    ("Cápsula endoscópica", "Como funciona a cápsula endoscópica?",
     "Você engole uma cápsula do tamanho de um comprimido grande, com uma câmera pequena. Ela tira muitas fotos enquanto percorre o intestino e as envia para um gravador preso ao seu corpo. Depois, o médico analisa as imagens.", _MAL),
    ("Cápsula endoscópica", "Como a cápsula sai do meu corpo?",
     "Ela é eliminada naturalmente nas fezes, sem dor. Na maioria das pessoas isso ocorre em poucos dias. A cápsula é descartável e não precisa ser recuperada.", _ENC),
    ("Cápsula endoscópica", "Preciso procurar a cápsula nas fezes?",
     "Não. Ela é descartável e você pode dar a descarga normalmente. Se a equipe quiser confirmar que saiu, ela pode indicar um exame de imagem.", _WES),
    ("Cápsula endoscópica", "E se a cápsula demorar para sair?",
     "Avise a equipe da clínica se não tiver certeza de que ela foi eliminada dentro do prazo informado. Se houver dor, enjoo persistente, vômito ou barriga que vai inchando, procure atendimento.", _ENC),
    ("Cápsula endoscópica", "Posso fazer ressonância magnética depois de engolir a cápsula?",
     "Não até a equipe confirmar que a cápsula foi eliminada. Avise sobre qualquer exame marcado para os próximos dias.", _ENC),
    ("Cápsula endoscópica", "Que roupa devo usar no dia da cápsula endoscópica?",
     "Use duas blusas abertas na frente. A de baixo fica sob o cinto ou os sensores e a de cima por cima do equipamento. Roupas folgadas facilitam o uso do gravador por todo o exame.", _ENC),
    ("Cápsula endoscópica", "Posso me movimentar e trabalhar durante o exame?",
     "Sim, dentro do possível. Depois de engolir a cápsula você pode se mover livremente e fazer atividades leves. Evite esforço intenso e campos magnéticos fortes.", _WES),
    ("Cápsula endoscópica", "Quando posso comer e beber durante o exame?",
     "Depois de certo tempo, primeiro líquidos claros e mais tarde uma refeição leve. Os tempos estão no seu preparo. Evite alimentos vermelhos ou roxos, verduras com fibras, café e chá, se essa for a orientação da sua clínica.", _ENC),
    ("Cápsula endoscópica", "Quando posso tomar meus remédios durante o exame?",
     "Em geral, após um período depois de engolir a cápsula. Confira o horário no seu preparo e retome os remédios de rotina depois do exame, se foi orientado.", _ENC),
    ("Cápsula endoscópica", "Tenho marca-passo, posso fazer o exame?",
     "Marca-passo e outros dispositivos eletrônicos implantados costumam ser contraindicações ou exigem cuidado especial. Avise a equipe da clínica antes do agendamento.", _ALTA),
    ("Cápsula endoscópica", "Gestantes podem fazer cápsula endoscópica?",
     "A gravidez costuma estar entre as situações em que o exame não é indicado. Se estiver grávida ou suspeitar, avise a clínica antes.", _MAL),
    ("Cápsula endoscópica", "Tenho dificuldade para engolir, posso fazer o exame?",
     "Problemas de deglutição, estreitamento ou obstrução no intestino são situações que exigem avaliação prévia. Informe a equipe para que ela decida a melhor forma de fazer o exame.", _MAL),
    ("Cápsula endoscópica", "Qual é o principal risco da cápsula endoscópica?",
     "É a cápsula ficar retida no trato digestivo, o que é raro. Se isso ocorrer, pode ser necessário retirá-la por endoscopia ou cirurgia. Informe cirurgias anteriores e problemas no intestino.", _WES),
    ("Cápsula endoscópica", "Quais sinais durante ou depois do exame exigem atenção?",
     "Febre, engasgo, dor no peito, dor na barriga que aumenta, vômitos ou enjoo persistente. Procure atendimento e avise a clínica.", _WES),
    ("Cápsula endoscópica", "Posso passar creme ou pomada na barriga antes do exame?",
     "Não. Cremes e pomadas na região do abdome podem atrapalhar a fixação dos sensores. Siga as orientações da sua clínica.", _ENC),
    ("Cápsula endoscópica", "Preciso evitar algum alimento antes do exame?",
     "Sim. Costuma-se evitar sementes, pipoca, milho, farelos e castanhas. Também alimentos vermelhos ou roxos, leite e verduras fibrosas na véspera, conforme o seu preparo.", _ENC),
    ("Cápsula endoscópica", "Vou precisar usar laxante ou algum remédio para gases?",
     "Alguns preparos incluem laxante para limpar o intestino e um remédio antiespumante tomado antes de engolir a cápsula. Siga a orientação que recebeu.", _MAL),
    ("Cápsula endoscópica", "O que faço com o gravador no fim do exame?",
     "Depois do tempo indicado, você retira o cinto e o gravador e devolve à equipe. Só então as imagens são baixadas e analisadas.", _ECL),
    ("Cápsula endoscópica", "Como sai o resultado da cápsula?",
     "As imagens são convertidas em vídeo e analisadas pelo médico, que faz o laudo final. O prazo de entrega é informado pela clínica.", _ALTA),
    ("Cápsula endoscópica", "A cápsula endoscópica dói?",
     "Não. Não há introdução de aparelhos pelo corpo. Você engole a cápsula com água e o restante do exame é por conta do intestino, então costuma ser mais confortável que outros exames.", _MAL),
    ("Cápsula endoscópica", "Preciso avisar sobre cirurgias no abdome ou sobre marca-passo?",
     "Sim. Informe marca-passo, cirurgias anteriores, dificuldade para engolir e histórico de obstrução intestinal. Isso ajuda a equipe a decidir a melhor forma de fazer o exame.", _WES),

    # ---------------- Ecoendoscopia ----------------
    ("Ecoendoscopia", "Qual a diferença entre ecoendoscopia e endoscopia comum?",
     "A ecoendoscopia junta a endoscopia com um ultrassom na ponta do aparelho. Assim, além da superfície, ela mostra as camadas da parede e órgãos vizinhos, como o pâncreas e a vesícula.", _DAE),
    ("Ecoendoscopia", "Como é feita a ecoendoscopia?",
     "Um aparelho flexível com câmera e ultrassom é introduzido pela boca ou, em alguns casos, pelo ânus, com você sedado. As imagens aparecem em tela em tempo real. Se necessário, pode ser colhido material.", _DAE),
    ("Ecoendoscopia", "O que é a ecoendoscopia com punção?",
     "É a mesma ecoendoscopia, mas com uma agulha fina que colhe amostra de uma lesão para análise. É feita com o paciente sedado.", _RDP),
    ("Ecoendoscopia", "Com quanto tempo de antecedência devo chegar e o que levar?",
     "Chegue com folga, no tempo informado pela unidade. Leve pedido médico, carteirinha do convênio, CPF, documento com foto e exames anteriores relacionados.", _RDA),
    ("Ecoendoscopia", "Posso beber álcool antes da ecoendoscopia?",
     "Evite. O preparo pede que a bebida alcoólica fique de fora no período indicado antes do exame. Siga o tempo do seu preparo.", _RDA),
    ("Ecoendoscopia", "Posso ir com joias, esmalte ou cabelo molhado?",
     "Não. Deixe joias em casa, retire o esmalte e evite cabelo molhado, pois isso pode interferir nos equipamentos de monitoramento.", _RDA),
    ("Ecoendoscopia", "Tenho alergia a látex, preciso avisar?",
     "Sim, avise no agendamento. Em alguns serviços a alergia a látex impede a realização do exame no formato padrão.", _RDA),
    ("Ecoendoscopia", "Estou gripado ou com febre, posso fazer o exame?",
     "Infecção respiratória recente, febre, tosse ou resfriado podem impedir o exame por causa da sedação. Avise a equipe da clínica antes de ir.", _RDA),
    ("Ecoendoscopia", "Tenho desfibrilador implantado, isso muda algo?",
     "Sim. O exame pode precisar ser feito em ambiente hospitalar. Avise a equipe no agendamento.", _RDA),
    ("Ecoendoscopia", "Tenho problema no coração, preciso de algum documento?",
     "Algumas clínicas pedem uma carta de liberação da cardiologia para quem tem doença cardíaca. Confira a lista do seu agendamento.", _ENE),
    ("Ecoendoscopia", "Como tomo meus remédios de pressão e coração no dia do exame?",
     "Em geral podem ser tomados ao acordar com pouca água, se essa for a orientação do seu preparo. Já remédios para diabetes e injeções para afinar o sangue costumam ficar de fora. Siga o seu preparo.", _ENE),
    ("Ecoendoscopia", "Preciso parar ferro ou remédio para emagrecer?",
     "Alguns preparos pedem a suspensão de sulfato ferroso e de certos remédios para emagrecer pelo tempo indicado. Avise a equipe sobre tudo o que você usa.", _ENE),
    ("Ecoendoscopia", "O que comer na véspera da ecoendoscopia?",
     "Reduza alimentos gordurosos e faça uma refeição leve no jantar, com boa antecedência antes de deitar. Evite álcool.", _ENE),
    ("Ecoendoscopia", "Posso usar salto alto ou batom?",
     "Melhor evitar. Prefira roupas e calçados confortáveis, sem maquiagem forte no rosto ou esmalte escuro. Retire óculos, próteses dentárias e acessórios.", _ENE),
    ("Ecoendoscopia", "Preciso fazer exames de sangue antes?",
     "Em alguns casos a equipe pede exames de sangue e de coagulação antes do procedimento, principalmente quando pode haver punção. Siga o que estiver no seu pedido.", _DAE),
    ("Ecoendoscopia", "A ecoendoscopia por via retal precisa de preparo do intestino?",
     "Sim. Quando o reto será avaliado, o preparo é semelhante ao da retossigmoidoscopia. Siga a orientação específica da sua clínica.", _GLF),
    ("Ecoendoscopia", "A ecoendoscopia é segura?",
     "É considerada segura, com poucas complicações, sobretudo quando há punção. A equipe monitora você durante todo o procedimento.", _GLF),
    ("Ecoendoscopia", "Quem faz a sedação da ecoendoscopia?",
     "Em muitos serviços, um anestesista faz a sedação profunda e acompanha você durante o exame.", _GLF),
    ("Ecoendoscopia", "Posso fazer o exame sem acompanhante?",
     "Não. Sem acompanhante adulto o procedimento não é realizado. Ele deve levar documento e ficar até o fim.", _RDP),
    ("Ecoendoscopia", "Meu filho menor de idade pode fazer o exame?",
     "Sim, mas o responsável legal deve acompanhar e assinar. Siga o preparo que a clínica informar para a idade da criança.", _ENE),
    ("Ecoendoscopia", "É normal ter a garganta irritada depois?",
     "Sim. Uma leve irritação na garganta é comum. Você fica em observação até a sedação passar e depois descansa pelo resto do dia.", _RDA),
    ("Ecoendoscopia", "Quando sai o resultado da ecoendoscopia?",
     "O prazo varia conforme a unidade e se houve punção ou biópsia, que exigem análise. A equipe informa como e quando retirar.", _RDA),
    ("Ecoendoscopia", "Posso retomar minhas atividades no mesmo dia?",
     "Não. O ideal é sair acompanhado e repousar o resto do dia, sem dirigir, por causa da sedação.", _ENE),
    ("Ecoendoscopia", "Quais alimentos e líquidos posso tomar antes do exame?",
     "O jejum é total no período indicado, incluindo água. A regra muda conforme seja exame pela manhã ou à tarde, então siga o seu preparo.", _RDA),
]
