# -*- coding: utf-8 -*-
ITENS = [
    ("Urina tipo 1 e urocultura", "Preciso ficar em jejum para colher a urina?",
     "Não é preciso jejum para a urina tipo 1 nem para a urocultura. Você pode se alimentar normalmente. O que importa mais é a higiene e a forma de coletar.",
     ("Rede D'Or São Luiz - Urocultura", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/urocultura")),
    ("Urina tipo 1 e urocultura", "Posso beber bastante água antes de coletar a urina?",
     "Beba líquidos de forma normal, sem exagerar. Muita água dilui a amostra e pode atrapalhar a leitura, principalmente na urocultura. Mantenha a hidratação habitual.",
     ("Laboratório Santa Catarina - Como coletar urina", "https://laboratoriosc.com.br/exame-de-urina-como-coletar-corretamente/")),
    ("Urina tipo 1 e urocultura", "Posso usar um pote de casa em vez do frasco do laboratório?",
     "Não é o ideal. O frasco fornecido pelo laboratório é estéril e evita contaminação, o que é importante para não alterar o resultado. Potes reaproveitados aumentam o risco de a amostra ser recusada.",
     ("Lafê - Exame de urina", "https://www.lafelab.com.br/noticias/exame-de-urina")),
    ("Urina tipo 1 e urocultura", "Sou mulher, como devo fazer a limpeza e a coleta na prática?",
     "Lave as mãos e limpe a região com água e sabão neutro, sempre da frente para trás. Durante a coleta, mantenha os lábios afastados para a urina não tocar a pele. Depois enxágue bem e seque com toalha limpa ou gaze.",
     ("Laboratório Santa Catarina - Como coletar urina", "https://laboratoriosc.com.br/exame-de-urina-como-coletar-corretamente/")),
    ("Urina tipo 1 e urocultura", "Sou homem, como faço a higiene antes da coleta?",
     "Lave as mãos e depois a glande com água e sabão, puxando a pele que a recobre para trás. Enxágue bem, seque e mantenha essa pele afastada durante a coleta. Assim a urina não passa por áreas com bactérias da pele.",
     ("Hospital Dom Alvarenga - Urina tipo I e urocultura", "https://hospitalalvarenga.com.br/exames/urina-tipo-i-urocultura/")),
    ("Urina tipo 1 e urocultura", "Meu bebê ainda usa fralda, como coletar a urina dele?",
     "Em crianças sem controle da urina costuma-se usar um saco coletor próprio, colado depois de higienizar bem a região. Em muitos casos a coleta é feita na própria unidade, com orientação. Se o saco ficar com fezes, a amostra deve ser descartada e a coleta refeita.",
     ("Laboratório de Análises Clínicas UFBA - Urocultura", "https://lactfar.far.ufba.br/urocultura")),
    ("Urina tipo 1 e urocultura", "Uso sonda vesical, como é feita a coleta?",
     "Na coleta por sonda, a amostra é retirada de forma cuidadosa pela equipe de saúde, seguindo o protocolo do serviço. Não abra o sistema por conta própria. Avise que você usa sonda ao agendar o exame.",
     ("Laboratório de Análises Clínicas UFBA - Urocultura", "https://lactfar.far.ufba.br/urocultura")),
    ("Urina tipo 1 e urocultura", "Terminei o antibiótico há pouco, já posso fazer a urocultura?",
     "Alguns laboratórios pedem um intervalo depois do fim do antibiótico para o resultado ser confiável. Esse intervalo está no seu preparo. Se a coleta for antes de começar o remédio, isso também costuma ser recomendado.",
     ("Lafê - Exame de urina", "https://www.lafelab.com.br/noticias/exame-de-urina")),
    ("Urina tipo 1 e urocultura", "Fiz exame com contraste ou usei creme vaginal, isso atrapalha?",
     "Sim, pode atrapalhar. Contraste radiológico e cremes vaginais podem alterar a urina. Avise a equipe sobre exames recentes e produtos que você usou, e siga o intervalo descrito no seu preparo.",
     ("Centro Médico de Sorocaba - Instrução de coleta de urina tipo I", "https://www.centromedicosorocaba.com.br/imagens/exame/5682b49e2edd9c7926efad10b5c7eb88.pdf")),
    ("Urina tipo 1 e urocultura", "Preciso avisar sobre vitaminas e suplementos que tomo?",
     "Sim. Informe todos os medicamentos, vitaminas e suplementos que você usa, além de diuréticos e antibióticos. Algumas substâncias mudam a cor ou a composição da urina. Se puder, leve uma lista ou foto do que toma.",
     ("Lafê - Exame de urina", "https://www.lafelab.com.br/noticias/exame-de-urina")),
    ("Urina tipo 1 e urocultura", "Como devo identificar o frasco depois da coleta?",
     "Escreva seu nome, a data e o horário da coleta no corpo do frasco. Evite escrever só na tampa, porque ela pode se separar do frasco. O horário ajuda o laboratório a saber se a amostra está dentro do tempo aceito.",
     ("Portal Afya - Orientações para cultura de urina", "https://portal.afya.com.br/clinica-medica/orientacoes-ao-paciente-para-evitar-a-contaminacao-da-amostra-na-cultura-de-urina")),
    ("Urina tipo 1 e urocultura", "Preciso encher o frasco inteiro?",
     "Não é preciso encher. Basta colocar urina até mais ou menos a metade do frasco, como diz a instrução do laboratório. Encher demais não ajuda e pode causar vazamento.",
     ("Centro Médico de Sorocaba - Instrução de coleta de urina tipo I", "https://www.centromedicosorocaba.com.br/imagens/exame/5682b49e2edd9c7926efad10b5c7eb88.pdf")),
    ("Urina tipo 1 e urocultura", "Encostei a mão na parte de dentro da tampa, o que faço?",
     "Avise a equipe do laboratório e, se possível, peça um frasco novo para repetir a coleta. Tocar o interior do frasco ou da tampa é um dos erros mais comuns e pode contaminar a amostra.",
     ("Lafê - Exame de urina", "https://www.lafelab.com.br/noticias/exame-de-urina")),
    ("Urina tipo 1 e urocultura", "Posso deixar o frasco no sol ou no carro até chegar ao laboratório?",
     "Não. Evite calor e luz direta do sol, pois isso altera a urina. Leve o frasco protegido e entregue o quanto antes, ou guarde como o seu preparo orientar.",
     ("Centro Médico de Sorocaba - Instrução de coleta de urina tipo I", "https://www.centromedicosorocaba.com.br/imagens/exame/5682b49e2edd9c7926efad10b5c7eb88.pdf")),
    ("Urina tipo 1 e urocultura", "Tenho dificuldade para me locomover, existe alternativa para coletar?",
     "Algumas unidades oferecem atendimento domiciliar para quem tem mobilidade reduzida. Pergunte à equipe sobre essa opção ao agendar. O conforto e a segurança da pessoa são prioridade.",
     ("Lafê - Exame de urina", "https://www.lafelab.com.br/noticias/exame-de-urina")),
    ("Urina tipo 1 e urocultura", "O que significa urocultura negativa ou positiva, em termos gerais?",
     "Negativa quer dizer que não houve crescimento de bactérias ou fungos na amostra. Positiva significa que algum microrganismo cresceu, e o laudo costuma informar qual é e a que remédios ele responde. A interpretação é feita pela equipe que pediu o exame.",
     ("Rede D'Or São Luiz - Urocultura", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/urocultura")),
    ("Urina tipo 1 e urocultura", "Por que a urocultura demora mais para sair que a urina tipo 1?",
     "Na urocultura a amostra fica em cultura para as bactérias crescerem, e isso leva mais tempo do que a análise da urina comum. O prazo varia conforme o laboratório e está informado no seu comprovante.",
     ("Rede D'Or São Luiz - Urocultura", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/urocultura")),
    ("Urina tipo 1 e urocultura", "Uma coleta malfeita pode dar resultado errado?",
     "Pode. Higiene incompleta, contaminação, armazenamento inadequado e demora na entrega podem gerar resultados que não correspondem à realidade. Por isso vale seguir o passo a passo com calma.",
     ("Rede D'Or São Luiz - Urocultura", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/urocultura")),

    ("Parasitológico de fezes", "Preciso ficar em jejum para o parasitológico?",
     "Não. Esse exame não exige jejum e você pode se alimentar normalmente. Fique atenta ou atento apenas às orientações sobre remédios e alimentos do seu preparo.",
     ("Laboratório Carlos Chagas - Parasitológico de fezes", "https://www.laboratoriocarloschagas.com.br/exame-parasitologico-de-fezes-tire-todas-as-suas-duvidas/")),
    ("Parasitológico de fezes", "Existe algum alimento que devo evitar antes da coleta?",
     "Algumas orientações pedem para evitar carnes vermelhas e malpassadas pouco antes, além de alimentos muito gordurosos. Siga o que está no seu preparo. Se não houver restrição, mantenha a alimentação habitual.",
     ("Laboratório Carlos Chagas - Parasitológico de fezes", "https://www.laboratoriocarloschagas.com.br/exame-parasitologico-de-fezes-tire-todas-as-suas-duvidas/")),
    ("Parasitológico de fezes", "Quais remédios podem atrapalhar o resultado?",
     "Antiparasitários, antibióticos, antidiarreicos e anti-inflamatórios podem interferir, assim como óleo mineral e alguns produtos usados em exames de imagem. O intervalo sem esses itens está no seu preparo. Avise a equipe sobre tudo o que tomou.",
     ("Laboratório Carlos Chagas - Parasitológico de fezes", "https://www.laboratoriocarloschagas.com.br/exame-parasitologico-de-fezes-tire-todas-as-suas-duvidas/")),
    ("Parasitológico de fezes", "Fiz exame com contraste, posso coletar logo depois?",
     "Melhor esperar. O contraste usado em radiografias pode atrapalhar a leitura das fezes. Siga o intervalo indicado no seu preparo e avise a equipe se fez o exame recentemente.",
     ("Rede D'Or São Luiz - Parasitológico", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/parasitologico")),
    ("Parasitológico de fezes", "Por que o laboratório pede várias amostras em ocasiões diferentes?",
     "Porque parasitas podem liberar ovos e cistos de forma intermitente. Uma coleta única pode não pegar esse momento. Por isso as amostras são feitas em ocasiões separadas, seguindo o espaçamento do seu preparo.",
     ("Dasa - Parasitológico de fezes", "https://nav.dasa.com.br/blog/parasitologico-fezes")),
    ("Parasitológico de fezes", "Posso coletar direto no vaso sanitário?",
     "Não. A água e os produtos de limpeza do vaso contaminam a amostra. Evacue em um recipiente limpo e seco, ou sobre plástico ou papel seco, e depois transfira a porção para o frasco.",
     ("Lafê - Exame de fezes", "https://www.lafelab.com.br/noticias/exame-de-fezes")),
    ("Parasitológico de fezes", "Minhas fezes têm muco ou sangue, coleto essa parte?",
     "Sim, é recomendado incluir as partes com muco ou sangue na amostra, pois podem conter mais parasitas. Se preferir, avise a equipe sobre o aspecto das fezes ao entregar o frasco.",
     ("Dasa - Parasitológico de fezes", "https://nav.dasa.com.br/blog/parasitologico-fezes")),
    ("Parasitológico de fezes", "Como coletar as fezes de uma criança que usa fralda?",
     "Recolha as fezes da fralda logo depois da evacuação, tentando pegar a parte que não encostou em urina. Depois transfira para o frasco com a pazinha. Siga o restante do seu preparo normalmente.",
     ("Saúde Naval - Orientações Parasitológico, MIF e Sangue Oculto", "https://www.marinha.mil.br/saudenaval/parasitologico-mif-fezes")),
    ("Parasitológico de fezes", "Estou com diarreia, como faço a coleta?",
     "Em casos de diarreia a coleta pode exigir um método especial, e o próprio laboratório costuma fornecer o material adequado. Avise a equipe antes de coletar para receber a orientação correta.",
     ("Laboratório Carlos Chagas - Parasitológico de fezes", "https://www.laboratoriocarloschagas.com.br/exame-parasitologico-de-fezes-tire-todas-as-suas-duvidas/")),
    ("Parasitológico de fezes", "Preciso escrever meu nome no frasco antes de coletar?",
     "Sim, é bom identificar o frasco com seu nome antes de começar, assim a amostra não se confunde com outra. Confira também se o pedido tem o seu nome correto.",
     ("Dasa - Parasitológico de fezes", "https://nav.dasa.com.br/blog/parasitologico-fezes")),
    ("Parasitológico de fezes", "Quando devo entregar o frasco ao laboratório?",
     "Entregue assim que possível. O prazo e a forma de guardar dependem do tipo de frasco e estão descritos no seu preparo. Se houver atraso, avise a equipe na entrega.",
     ("Laboratório Carlos Chagas - Parasitológico de fezes", "https://www.laboratoriocarloschagas.com.br/exame-parasitologico-de-fezes-tire-todas-as-suas-duvidas/")),
    ("Parasitológico de fezes", "O que o parasitológico consegue identificar?",
     "Ele procura ovos, cistos e larvas de parasitas intestinais, como vermes, amebas e giárdia. O laudo indica se algo foi encontrado e de que tipo. A interpretação é feita pela equipe que solicitou o exame.",
     ("Rede D'Or São Luiz - Parasitológico", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/parasitologico")),
    ("Parasitológico de fezes", "Se o resultado vier negativo, quer dizer que não tenho parasita?",
     "Nem sempre. Um resultado negativo indica que nada foi visto naquela amostra, mas os parasitas podem passar despercebidos, principalmente em coleta única. Por isso novas coletas podem ser pedidas.",
     ("Dasa - Parasitológico de fezes", "https://nav.dasa.com.br/blog/parasitologico-fezes")),

    ("Pesquisa de sangue oculto e calprotectina fecal", "Posso coletar se estou com hemorroidas sangrando?",
     "O ideal é evitar, porque o sangue das hemorroidas pode dar resultado alterado. Avise a equipe da clínica e combine a melhor data para coletar. O mesmo vale para sangramento visível na urina ou na menstruação.",
     ("Dirceu Dalpino - Sangue oculto nas fezes", "https://dirceudalpino.com.br/instrucoes-coleta/pesquisa-de-sangue-oculto-nas-fezes/")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Sangramento na gengiva pode atrapalhar o exame?",
     "Pode, se você engolir sangue. Escove os dentes e use fio dental com cuidado antes da coleta. Se houver sangramento, informe a equipe ao entregar a amostra.",
     ("Dirceu Dalpino - Sangue oculto nas fezes", "https://dirceudalpino.com.br/instrucoes-coleta/pesquisa-de-sangue-oculto-nas-fezes/")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Bebida alcoólica interfere no exame de sangue oculto?",
     "Algumas orientações pedem para evitar álcool pelo período do preparo, porque ele pode irritar o estômago e o intestino. Siga o que está no seu preparo. Se não houver essa instrução, avise a equipe se você bebeu recentemente.",
     ("Diagnósticos do Brasil - Sangue oculto", "https://laborclinica.com/service/pesquisa-de-sangue-oculto-nas-fezes/")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Existe teste de sangue oculto que dispensa dieta e suspensão de remédios?",
     "Sim, os testes imunológicos mais modernos costumam dispensar restrições alimentares e de medicamentos. Mesmo assim, cada laboratório tem sua regra. Siga a que está no seu preparo.",
     ("Rede D'Or São Luiz - Pesquisa de sangue oculto", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/pesquisa-sangue-oculto")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Preciso evitar laxantes ou supositórios antes de coletar?",
     "Em geral sim, pelo período informado no seu preparo. Laxantes, supositórios e contrastes orais podem alterar a amostra. Use apenas o que a equipe indicar.",
     ("Laboratório Laborclínica - Sangue oculto", "https://laborclinica.com/service/pesquisa-de-sangue-oculto-nas-fezes/")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Tenho intestino preso, como consigo coletar?",
     "Alimentos ricos em fibras ajudam o intestino a funcionar. Se for preciso usar algum laxante, isso deve ser feito só com orientação e informado à equipe. Nunca use por conta própria antes de saber se pode.",
     ("Diagnósticos do Brasil - Calprotectina", "https://gde.diagnosticosdobrasil.com.br/GDE_Home/DetalheDoExame.aspx?ExameId=CALPR")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Posso pegar as fezes da água do vaso ou misturadas com urina?",
     "Não. Evacue em um recipiente limpo e seco e evite contato com água do vaso e urina. Depois use a espátula do frasco para coletar a porção necessária.",
     ("Laboratório LAPEC - Calprotectina fecal", "https://www.lapeclab.uniexames.com.br/instrucoes/view?id=CALP")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Até onde devo encher o frasco?",
     "Basta cerca de metade da capacidade ou até a marca indicada no frasco. Não é preciso encher por completo. Se possível, colha de pontos diferentes das fezes.",
     ("Diagnósticos do Brasil - Calprotectina", "https://gde.diagnosticosdobrasil.com.br/GDE_Home/DetalheDoExame.aspx?ExameId=CALPR")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Se o pedido for para mais de uma amostra, como espaçar as coletas?",
     "Faça cada coleta em evacuações separadas, respeitando o intervalo indicado no seu preparo. Não junte fezes de evacuações diferentes no mesmo frasco. Identifique cada frasco.",
     ("a+ Medicina Diagnóstica - Sangue oculto", "https://www.amaissaude.com.br/sp/exames/sangue-oculto-pesquisa-fezes")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Para a calprotectina, preciso coletar a primeira evacuação da manhã?",
     "Algumas instruções preferem a primeira evacuação do dia, então vale seguir o seu preparo. Lembre de evitar urina na amostra. Se não conseguir na manhã, avise a equipe.",
     ("Laboratório LAPEC - Calprotectina fecal", "https://www.lapeclab.uniexames.com.br/instrucoes/view?id=CALP")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Como devo guardar a amostra até entregar?",
     "Muitos laboratórios pedem refrigeração enquanto a amostra não chega. Evite congelar por conta própria, pois isso pode alterar o resultado. Siga o modo de guardar e o prazo do seu preparo.",
     ("Laboratório LAPEC - Calprotectina fecal", "https://www.lapeclab.uniexames.com.br/instrucoes/view?id=CALP")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Se minhas fezes tiverem sangue visível, posso entregar assim?",
     "Avise a equipe antes de coletar. Alguns laboratórios não aceitam amostras com sangue visível para certas dosagens e podem orientar de outro jeito. Não descarte nada sem falar com a equipe.",
     ("Diagnósticos do Brasil - Calprotectina", "https://gde.diagnosticosdobrasil.com.br/GDE_Home/DetalheDoExame.aspx?ExameId=CALPR")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "A calprotectina substitui a colonoscopia?",
     "Não. Ela ajuda como triagem, mostrando se há sinais de inflamação no intestino. Outros exames podem continuar sendo necessários, conforme a equipe que pediu.",
     ("Rede D'Or São Luiz - Calprotectina fecal", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/calprotectina-fecal")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Um resultado positivo de sangue oculto já significa algo grave?",
     "Não necessariamente. Vários motivos podem gerar resultado positivo, e a equipe de saúde avalia o conjunto de informações. O resultado sozinho não fecha nenhuma conclusão.",
     ("Rede D'Or São Luiz - Pesquisa de sangue oculto", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/pesquisa-sangue-oculto")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Posso coletar em casa?",
     "Sim, a coleta costuma ser feita em casa com o kit fornecido pelo laboratório. Siga as instruções do kit e depois leve ou envie a amostra como combinado.",
     ("Rede D'Or São Luiz - Pesquisa de sangue oculto", "https://www.rededorsaoluiz.com.br/exames-e-procedimentos/analises-clinicas/pesquisa-sangue-oculto")),
    ("Pesquisa de sangue oculto e calprotectina fecal", "Como coletar de uma criança de fralda ou com diarreia?",
     "Alguns laboratórios indicam um coletor próprio, como um saco coletor, para não misturar com a fralda ou perder a amostra. Peça esse material ao laboratório e siga a orientação recebida.",
     ("a+ Medicina Diagnóstica - Sangue oculto", "https://www.amaissaude.com.br/sp/exames/sangue-oculto-pesquisa-fezes")),
