# -*- coding: utf-8 -*-
"""Itens de FAQ de preparo de exames (grupo 3). Sem imports do projeto."""

_HCPA = ("Hospital de Clínicas de Porto Alegre - Guia de preparo de pacientes para exames radiológicos e de imagem", "https://www.hcpa.edu.br/downloads/cgp_ensino/14._produto_-guia_informativo_preparo_de_pacientes_para_exames_radiologicos_e_de_imagem_1.pdf")
_TIREOIDE = ("Saúde Naval - Orientações para cintilografia de tireoide", "https://www.marinha.mil.br/saudenaval/cintilografia-de-tireoide")
_OSSEA = ("Saúde Naval - Orientações para cintilografia óssea", "https://www.marinha.mil.br/saudenaval/cintilografia-ossea")
_RENAL = ("Saúde Naval - Orientações para cintilografia renal", "https://www.marinha.mil.br/saudenaval/cintilografia-renal")
_PET = ("Saúde Naval - Orientações para PET Scan", "https://www.marinha.mil.br/saudenaval/orientacoes-para-pet-scan")
_MIOCARDIO = ("Prefeitura de São Paulo - Orientação para cintilografia de perfusão miocárdica", "https://drive.prefeitura.sp.gov.br/cidade/secretarias/upload/saude/cintilografia.pdf")

ITENS = [
    # Radiografia contrastada do esôfago, estômago e duodeno
    ("Radiografia contrastada do esôfago, estômago e duodeno",
     "Preciso ficar em jejum para a radiografia do esôfago, estômago e duodeno?",
     "Sim, o estômago precisa estar vazio para o contraste aparecer bem nas imagens. Siga o tempo de jejum indicado no seu preparo. Nesse período, evite também fumar e mascar chiclete.",
     _HCPA),
    ("Radiografia contrastada do esôfago, estômago e duodeno",
     "Posso tomar meus remédios de rotina antes da radiografia contrastada do estômago?",
     "Em geral, o jejum vale para comida e bebida, e os remédios de rotina tomados pela boca costumam ser a exceção. Mesmo assim, siga o que estiver escrito no seu preparo. Se tiver alguma dúvida sobre um medicamento específico, avise a equipe da clínica.",
     _HCPA),
    ("Radiografia contrastada do esôfago, estômago e duodeno",
     "O que é o contraste que vou tomar na radiografia do esôfago, estômago e duodeno?",
     "É um líquido à base de bário que você bebe durante o exame para que o esôfago, o estômago e o duodeno apareçam nas imagens. A equipe explica o passo a passo e orienta as posições em que você deve ficar. Se tiver dificuldade para engolir ou usar sonda, avise a equipe antes de começar.",
     _HCPA),
    ("Radiografia contrastada do esôfago, estômago e duodeno",
     "Estou grávida ou pode ser que esteja. Posso fazer a radiografia contrastada do estômago?",
     "Como o exame usa radiação, avise a equipe da clínica antes de começar se houver qualquer chance de gravidez. Assim a equipe decide junto com você como proceder com segurança. Não deixe essa informação para depois.",
     _HCPA),
    ("Radiografia contrastada do esôfago, estômago e duodeno",
     "Preciso levar acompanhante na radiografia contrastada do esôfago, estômago e duodeno?",
     "Se o seu preparo pedir acompanhante, leve alguém de confiança. Se você usa sonda nasogástrica ou tem alguma limitação, avise a equipe no agendamento para que tudo seja organizado com antecedência.",
     _HCPA),

    # Trânsito intestinal
    ("Trânsito intestinal",
     "Preciso de jejum para fazer o exame de trânsito intestinal?",
     "Sim, o jejum ajuda a deixar o intestino em condições de ser bem visualizado. Siga o tempo indicado no seu preparo e evite fumar e mascar chiclete nesse período. Só os remédios tomados pela boca costumam ficar de fora da suspensão, conforme o seu preparo.",
     _HCPA),
    ("Trânsito intestinal",
     "Posso tomar meus remédios no dia do trânsito intestinal?",
     "Os medicamentos de uso pela boca geralmente não entram na suspensão do jejum. Siga o que está escrito no seu preparo. Se usa algum remédio que gera dúvida, avise a equipe da clínica antes do exame.",
     _HCPA),
    ("Trânsito intestinal",
     "Como é o contraste do exame de trânsito intestinal?",
     "Você bebe um líquido à base de bário, e imagens são feitas em vários momentos para acompanhar a passagem do contraste pelo intestino. Por isso o exame pode ser demorado. Se tiver dificuldade para engolir ou usar sonda no nariz, avise a equipe.",
     _HCPA),
    ("Trânsito intestinal",
     "Uso sonda nasogástrica. Isso muda alguma coisa no trânsito intestinal?",
     "Sim, é importante avisar a equipe da clínica que você usa sonda. Ela pode ser usada para administrar o contraste, conforme a orientação da equipe. Informe isso já no agendamento.",
     _HCPA),
    ("Trânsito intestinal",
     "Posso fazer o trânsito intestinal estando grávida?",
     "O exame usa radiação, por isso avise a equipe da clínica antes de começar se houver qualquer chance de gravidez. A equipe vai orientar como proceder.",
     _HCPA),

    # Enema opaco
    ("Enema opaco",
     "Como é o preparo do intestino para o enema opaco?",
     "O intestino precisa estar limpo para as imagens ficarem nítidas. O preparo costuma incluir dieta leve na véspera, laxantes e líquidos, sempre nos momentos indicados no seu preparo. Siga cada etapa como está escrito e avise a equipe se tiver dificuldade.",
     _HCPA),
    ("Enema opaco",
     "O que posso comer na véspera do enema opaco?",
     "Costuma-se usar alimentos leves e de fácil digestão, como pão torrado, arroz, frango sem pele, batata cozida, caldos coados, gelatina e chá. Evite alimentos pesados ou com muitas fibras. Siga a lista exata do seu preparo.",
     _HCPA),
    ("Enema opaco",
     "Preciso de acompanhante no dia do enema opaco?",
     "Sim, é recomendado comparecer acompanhado, pois o preparo com laxantes pode deixar você cansado. Combine com alguém de confiança com antecedência.",
     _HCPA),
    ("Enema opaco",
     "Tenho colostomia ou megacólon. Posso fazer o preparo do enema opaco?",
     "Nesses casos, avise a equipe da clínica antes de iniciar qualquer preparo, porque a limpeza com enema pode não ser indicada para você. Não faça o preparo por conta própria até receber orientação da equipe.",
     _HCPA),
    ("Enema opaco",
     "Posso fazer o enema opaco se estiver grávida?",
     "O exame usa radiação, então avise a equipe da clínica antes de começar se houver qualquer chance de gravidez. A equipe vai orientar a melhor conduta.",
     _HCPA),

    # Urografia excretora
    ("Urografia excretora",
     "Preciso de jejum e laxante para a urografia excretora?",
     "Geralmente sim. O jejum e a limpeza do intestino ajudam a enxergar bem os rins e as vias urinárias. Siga o tempo de jejum e o laxante indicados no seu preparo, nos momentos combinados.",
     _HCPA),
    ("Urografia excretora",
     "Posso tomar meus remédios de rotina antes da urografia excretora?",
     "Em geral, os medicamentos de uso contínuo não devem ser suspensos por conta própria. Siga o que estiver escrito no seu preparo. Se tiver dúvida sobre algum remédio, avise a equipe da clínica.",
     _HCPA),
    ("Urografia excretora",
     "Tenho intestino preso. Devo fazer algo diferente no preparo da urografia excretora?",
     "Quem tem constipação pode precisar de um laxante adicional. Avise a equipe da clínica com antecedência para que o preparo seja ajustado. Não aumente o laxante por conta própria.",
     _HCPA),
    ("Urografia excretora",
     "Posso fazer a urografia excretora se estiver grávida?",
     "O exame usa radiação, então avise a equipe da clínica antes de começar se houver qualquer chance de gravidez.",
     _HCPA),
    ("Urografia excretora",
     "Tenho alergia a contraste. Preciso avisar antes da urografia excretora?",
     "Sim. O exame usa contraste injetado na veia, por isso informe a equipe sobre alergias, reações anteriores a contraste e problemas nos rins. Depois do exame, se surgir coceira, falta de ar ou inchaço, avise a equipe imediatamente.",
     _HCPA),

    # Uretrocistografia miccional
    ("Uretrocistografia miccional",
     "Preciso de preparo do intestino para a uretrocistografia miccional?",
     "Em adultos, costuma haver jejum e limpeza do intestino, conforme o seu preparo. Em crianças, geralmente não há preparo intestinal. Siga o que estiver escrito nas suas orientações.",
     _HCPA),
    ("Uretrocistografia miccional",
     "Posso tomar meus remédios antes da uretrocistografia miccional?",
     "Em geral, não é preciso suspender os medicamentos de rotina. Siga o seu preparo e avise a equipe da clínica sobre tudo o que você usa.",
     _HCPA),
    ("Uretrocistografia miccional",
     "Estou menstruada. Posso fazer a uretrocistografia miccional?",
     "Em geral, o exame só é feito durante o sangramento menstrual em casos de urgência. Avise a equipe da clínica para remarcar ou receber orientação.",
     _HCPA),
    ("Uretrocistografia miccional",
     "Uso sonda na bexiga. Como fica a uretrocistografia miccional?",
     "Avise a equipe da clínica. A sonda pode ser retirada e o procedimento será conduzido pelos profissionais de enfermagem, conforme a orientação recebida.",
     _HCPA),
    ("Uretrocistografia miccional",
     "Fiz um procedimento na uretra recentemente. Posso fazer a uretrocistografia miccional?",
     "Avise a equipe da clínica sobre o procedimento. Costuma ser necessário aguardar um período antes do exame, e a equipe informará quando é seguro fazer.",
     _HCPA),
    ("Uretrocistografia miccional",
     "Preciso fazer higiene antes da uretrocistografia miccional?",
     "Sim, faça a higiene íntima antes de sair de casa, conforme o seu preparo. Isso ajuda no conforto e na segurança do exame.",
     _HCPA),

    # Histerossalpingografia
    ("Histerossalpingografia",
     "Preciso de jejum para a histerossalpingografia?",
     "Sim, costuma haver um período curto de jejum antes do exame. Siga o tempo indicado no seu preparo e faça a limpeza do intestino na véspera, como orientado.",
     _HCPA),
    ("Histerossalpingografia",
     "Em que fase do ciclo menstrual posso fazer a histerossalpingografia?",
     "O exame costuma ser feito logo depois que a menstruação termina, sem sangramento e antes da ovulação. Siga as datas do seu preparo e avise a equipe da clínica se o ciclo mudar.",
     _HCPA),
    ("Histerossalpingografia",
     "Preciso evitar relação sexual antes da histerossalpingografia?",
     "Sim, a equipe precisa ter certeza de que você não está grávida. Por isso pode ser pedido evitar relação sexual ou usar preservativo antes do exame, além de um exame de gravidez, conforme o seu preparo.",
     _HCPA),
    ("Histerossalpingografia",
     "Preciso ir acompanhada à histerossalpingografia?",
     "Sim, é recomendado comparecer acompanhada. Faça a higiene íntima antes de sair de casa e esvazie a bexiga quando for chamada.",
     _HCPA),
    ("Histerossalpingografia",
     "Posso fazer a histerossalpingografia se ainda não tive relação sexual?",
     "Esse exame costuma ser contraindicado nessa situação. Avise a equipe da clínica para receber orientação sobre a melhor forma de prosseguir.",
     _HCPA),

    # Cintilografia do miocárdio
    ("Cintilografia do miocárdio",
     "Preciso ficar em jejum para a cintilografia do miocárdio?",
     "Costuma haver um período de jejum antes do exame e é bom evitar refeições pesadas. Siga o tempo e as regras do seu preparo.",
     _MIOCARDIO),
    ("Cintilografia do miocárdio",
     "Posso tomar café ou outras bebidas com cafeína antes da cintilografia do miocárdio?",
     "Geralmente não. Cafeína, chás, chocolate e alguns remédios que contêm cafeína podem atrapalhar o exame, principalmente quando ele usa remédio para estressar o coração. Evite-os pelo tempo indicado no seu preparo.",
     _MIOCARDIO),
    ("Cintilografia do miocárdio",
     "Preciso suspender meus remédios do coração antes da cintilografia do miocárdio?",
     "Isso depende do objetivo do exame. Em alguns casos alguns medicamentos precisam ser suspensos, em outros são mantidos. Siga rigorosamente o seu preparo e não suspenda nada por conta própria. Se tiver dúvida, avise a equipe da clínica.",
     _MIOCARDIO),
    ("Cintilografia do miocárdio",
     "Que roupa devo usar na cintilografia do miocárdio?",
     "Vá com roupa e calçado confortáveis, que permitam acesso ao peito. Retire correntes, moedas e outros objetos metálicos da região do tórax antes das imagens.",
     _MIOCARDIO),
    ("Cintilografia do miocárdio",
     "A cintilografia do miocárdio demora muito? Posso fazer se estiver grávida ou amamentando?",
     "O exame costuma levar boa parte da manhã ou da tarde, pois inclui etapas de repouso e de esforço ou estímulo. Gravidez e amamentação exigem cuidado, então avise a equipe da clínica antes de começar.",
     _MIOCARDIO),

    # Cintilografia da tireoide
    ("Cintilografia da tireoide",
     "Preciso ficar em jejum para a cintilografia da tireoide?",
     "Costuma ser pedido jejum no dia do exame. Siga o tempo indicado no seu preparo.",
     _TIREOIDE),
    ("Cintilografia da tireoide",
     "Preciso suspender o remédio da tireoide antes da cintilografia?",
     "Muitos remédios podem interferir no exame, entre eles hormônios da tireoide e remédios que contêm iodo. Siga o seu preparo sobre o que suspender e por quanto tempo, e não pare nada por conta própria. Avise a equipe da clínica sobre todos os medicamentos que usa.",
     _TIREOIDE),
    ("Cintilografia da tireoide",
     "Tenho que evitar algum alimento antes da cintilografia da tireoide?",
     "Sim. Alimentos ricos em iodo, como frutos do mar e peixes, além de algumas folhas verdes, podem atrapalhar o exame. Evite-os pelo período indicado no seu preparo.",
     _TIREOIDE),
    ("Cintilografia da tireoide",
     "Posso passar batom ou tintura de cabelo antes da cintilografia da tireoide?",
     "Alguns produtos, como batom, bronzeador e tintura de cabelo, podem conter iodo ou interferir. O seu preparo indica por quanto tempo evitá-los.",
     _TIREOIDE),
    ("Cintilografia da tireoide",
     "Posso ficar perto de crianças e amamentar depois da cintilografia da tireoide?",
     "Depois do exame há cuidados com a radiação. Costuma-se manter distância de crianças pequenas e suspender as mamadas por um período. Siga o que estiver no seu preparo e avise a equipe se estiver amamentando ou grávida.",
     _TIREOIDE),

    # Cintilografia óssea
    ("Cintilografia óssea",
     "Preciso ficar em jejum para a cintilografia óssea?",
     "O jejum não é a principal exigência. O mais importante é a hidratação. Siga o que estiver no seu preparo e, se ele indicar alguma restrição, cumpra-a.",
     _OSSEA),
    ("Cintilografia óssea",
     "Preciso beber água antes da cintilografia óssea?",
     "Sim, uma boa hidratação ajuda o exame. Beba água nas quantidades indicadas no seu preparo, tanto na véspera quanto no dia do exame. Não seguir essa orientação pode levar ao cancelamento.",
     _OSSEA),
    ("Cintilografia óssea",
     "Posso tomar meus remédios antes da cintilografia óssea?",
     "Em geral, os remédios de rotina são mantidos, a menos que o seu preparo diga o contrário. Avise a equipe da clínica sobre tudo o que você usa.",
     _OSSEA),
    ("Cintilografia óssea",
     "Posso fazer a cintilografia óssea se estiver grávida ou amamentando?",
     "Avise a equipe da clínica antes de começar. Como o exame usa uma pequena quantidade de material radioativo, a equipe orienta os cuidados necessários.",
     _OSSEA),
    ("Cintilografia óssea",
     "Preciso ter cuidado com outras pessoas depois da cintilografia óssea?",
     "Após o exame o material radioativo vai sendo eliminado principalmente pela urina. Continuar bebendo água e esvaziar a bexiga com frequência ajuda. Siga as orientações da equipe sobre contato com crianças e gestantes.",
     _OSSEA),

    # Cintilografia renal
    ("Cintilografia renal",
     "Preciso beber água antes da cintilografia renal?",
     "Sim, uma boa hidratação antes do exame costuma ser pedida, salvo se houver restrição de líquidos indicada pela sua equipe de saúde. Siga o seu preparo. Não seguir essa orientação pode levar ao cancelamento do exame.",
     _RENAL),
    ("Cintilografia renal",
     "Preciso ficar em jejum para a cintilografia renal?",
     "Depende do tipo de cintilografia renal. Siga as orientações do seu preparo sobre alimentação. Se não houver instrução de jejum, alimente-se de forma leve.",
     _RENAL),
    ("Cintilografia renal",
     "Posso tomar meus remédios de rotina antes da cintilografia renal?",
     "Em geral, sim, mas alguns exames podem exigir ajuste de certos medicamentos. Siga o que estiver no seu preparo e avise a equipe da clínica sobre tudo o que você usa.",
     _RENAL),
    ("Cintilografia renal",
     "Estou grávida ou amamentando. Posso fazer a cintilografia renal?",
     "Avise a equipe da clínica antes de começar. Ela vai orientar os cuidados necessários com a radiação.",
     _RENAL),
    ("Cintilografia renal",
     "Preciso de acompanhante na cintilografia renal?",
     "Depende do caso, principalmente para crianças e para quem precisa de ajuda. Se o seu preparo pedir, leve alguém. Fique tranquilo, o exame não dói e a equipe orienta cada etapa.",
     _RENAL),

    # PET-CT
    ("PET-CT",
     "Como é o jejum para o PET-CT?",
     "O jejum é importante para o exame ficar preciso. Siga o tempo indicado no seu preparo. Nesse período, evite exercícios, cigarro, cafeína e chiclete. Beber água costuma ser permitido e incentivado.",
     _PET),
    ("PET-CT",
     "Sou diabético. Como faço no PET-CT?",
     "O açúcar no sangue interfere no exame, por isso avise a equipe da clínica que você é diabético. A glicemia é medida antes da aplicação do contraste. Siga rigorosamente o seu preparo sobre insulina e outros remédios e não altere nada por conta própria.",
     _PET),
    ("PET-CT",
     "Posso tomar meus remédios de rotina antes do PET-CT?",
     "Não interrompa remédios por conta própria. Siga o seu preparo e avise a equipe da clínica sobre tudo o que usa.",
     _PET),
    ("PET-CT",
     "Estou grávida ou amamentando. Posso fazer o PET-CT?",
     "Avise a equipe da clínica antes do exame. Se estiver amamentando, costuma-se suspender as mamadas por um período e manter distância de crianças pequenas depois do exame. Siga as orientações da equipe.",
     _PET),
    ("PET-CT",
     "Tenho claustrofobia. Consigo fazer o PET-CT?",
     "O equipamento costuma ser aberto e a equipe acompanha você durante todo o exame. É importante ficar parado durante as imagens. Se tiver receio, avise a equipe antes de começar.",
     _PET),
    ("PET-CT",
     "O que levar e quanto tempo demora o PET-CT?",
     "Leve o pedido do exame e exames anteriores, como tomografias, ressonâncias e laudos de biópsia. O exame inclui espera após o contraste e costuma ser demorado. Depois, geralmente você retoma suas atividades normais.",
     _PET),

    # Densitometria óssea
    ("Densitometria óssea",
     "Preciso ficar em jejum para a densitometria óssea?",
     "Em geral, não é preciso jejum. Alimente-se de forma leve e siga o seu preparo.",
     _HCPA),
    ("Densitometria óssea",
     "Posso tomar cálcio ou vitaminas antes da densitometria óssea?",
     "Suplementos com cálcio, vitaminas e minerais costumam precisar ser suspensos antes do exame, pois podem alterar o resultado. Siga o período indicado no seu preparo. Os outros remédios de rotina, em geral, são mantidos.",
     _HCPA),
    ("Densitometria óssea",
     "Fiz um exame com contraste recentemente. Posso fazer a densitometria óssea?",
     "Contraste de tomografia, exame de medicina nuclear ou radiografia com bário podem atrapalhar o resultado. Avise a equipe da clínica e aguarde o intervalo indicado antes de fazer a densitometria.",
     _HCPA),
    ("Densitometria óssea",
     "Que roupa devo usar na densitometria óssea?",
     "Use roupa confortável, sem zíperes, botões ou peças de metal na região examinada. Deixe em casa joias, relógio e outros objetos metálicos.",
     _HCPA),
    ("Densitometria óssea",
     "Posso fazer a densitometria óssea se estiver grávida?",
     "O exame usa uma dose muito pequena de radiação, mas avise a equipe da clínica antes de começar se houver qualquer chance de gravidez. O exame é rápido e indolor.",
     _HCPA),
]
